// Code generated by ent, DO NOT EDIT.

package toolusage

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the toolusage type in the database.
	Label = "tool_usage"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldAgent holds the string denoting the agent field in the database.
	FieldAgent = "agent"
	// FieldTeam holds the string denoting the team field in the database.
	FieldTeam = "team"
	// FieldCommand holds the string denoting the command field in the database.
	FieldCommand = "command"
	// FieldSubcommand holds the string denoting the subcommand field in the database.
	FieldSubcommand = "subcommand"
	// FieldTarget holds the string denoting the target field in the database.
	FieldTarget = "target"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// Table holds the table name of the toolusage in the database.
	Table = "tool_usages"
)

// Columns holds all SQL columns for toolusage fields.
var Columns = []string{
	FieldID,
	FieldAgent,
	FieldTeam,
	FieldCommand,
	FieldSubcommand,
	FieldTarget,
	FieldCreatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// AgentValidator is a validator for the "agent" field. It is called by the builders before save.
	AgentValidator func(string) error
	// TeamValidator is a validator for the "team" field. It is called by the builders before save.
	TeamValidator func(string) error
	// CommandValidator is a validator for the "command" field. It is called by the builders before save.
	CommandValidator func(string) error
	// SubcommandValidator is a validator for the "subcommand" field. It is called by the builders before save.
	SubcommandValidator func(string) error
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)

// OrderOption defines the ordering options for the ToolUsage queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByAgent orders the results by the agent field.
func ByAgent(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAgent, opts...).ToFunc()
}

// ByTeam orders the results by the team field.
func ByTeam(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTeam, opts...).ToFunc()
}

// ByCommand orders the results by the command field.
func ByCommand(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCommand, opts...).ToFunc()
}

// BySubcommand orders the results by the subcommand field.
func BySubcommand(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSubcommand, opts...).ToFunc()
}

// ByTarget orders the results by the target field.
func ByTarget(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTarget, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}
