// Code generated by ent, DO NOT EDIT.

package toolusage

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
	"github.com/tta-lab/ttal-cli/internal/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.ToolUsage {
	return predicate.ToolUsage(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.ToolUsage {
	return predicate.ToolUsage(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.ToolUsage {
	return predicate.ToolUsage(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.ToolUsage {
	return predicate.ToolUsage(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.ToolUsage {
	return predicate.ToolUsage(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.ToolUsage {
	return predicate.ToolUsage(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.ToolUsage {
	return predicate.ToolUsage(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.ToolUsage {
	return predicate.ToolUsage(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.ToolUsage {
	return predicate.ToolUsage(sql.FieldLTE(FieldID, id))
}

// Agent applies equality check predicate on the "agent" field. It's identical to AgentEQ.
func Agent(v string) predicate.ToolUsage {
	return predicate.ToolUsage(sql.FieldEQ(FieldAgent, v))
}

// Team applies equality check predicate on the "team" field. It's identical to TeamEQ.
func Team(v string) predicate.ToolUsage {
	return predicate.ToolUsage(sql.FieldEQ(FieldTeam, v))
}

// Command applies equality check predicate on the "command" field. It's identical to CommandEQ.
func Command(v string) predicate.ToolUsage {
	return predicate.ToolUsage(sql.FieldEQ(FieldCommand, v))
}

// Subcommand applies equality check predicate on the "subcommand" field. It's identical to SubcommandEQ.
func Subcommand(v string) predicate.ToolUsage {
	return predicate.ToolUsage(sql.FieldEQ(FieldSubcommand, v))
}

// Target applies equality check predicate on the "target" field. It's identical to TargetEQ.
func Target(v string) predicate.ToolUsage {
	return predicate.ToolUsage(sql.FieldEQ(FieldTarget, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.ToolUsage {
	return predicate.ToolUsage(sql.FieldEQ(FieldCreatedAt, v))
}

// AgentEQ applies the EQ predicate on the "agent" field.
func AgentEQ(v string) predicate.ToolUsage {
	return predicate.ToolUsage(sql.FieldEQ(FieldAgent, v))
}

// AgentNEQ applies the NEQ predicate on the "agent" field.
func AgentNEQ(v string) predicate.ToolUsage {
	return predicate.ToolUsage(sql.FieldNEQ(FieldAgent, v))
}

// AgentIn applies the In predicate on the "agent" field.
func AgentIn(vs ...string) predicate.ToolUsage {
	return predicate.ToolUsage(sql.FieldIn(FieldAgent, vs...))
}

// AgentNotIn applies the NotIn predicate on the "agent" field.
func AgentNotIn(vs ...string) predicate.ToolUsage {
	return predicate.ToolUsage(sql.FieldNotIn(FieldAgent, vs...))
}

// AgentGT applies the GT predicate on the "agent" field.
func AgentGT(v string) predicate.ToolUsage {
	return predicate.ToolUsage(sql.FieldGT(FieldAgent, v))
}

// AgentGTE applies the GTE predicate on the "agent" field.
func AgentGTE(v string) predicate.ToolUsage {
	return predicate.ToolUsage(sql.FieldGTE(FieldAgent, v))
}

// AgentLT applies the LT predicate on the "agent" field.
func AgentLT(v string) predicate.ToolUsage {
	return predicate.ToolUsage(sql.FieldLT(FieldAgent, v))
}

// AgentLTE applies the LTE predicate on the "agent" field.
func AgentLTE(v string) predicate.ToolUsage {
	return predicate.ToolUsage(sql.FieldLTE(FieldAgent, v))
}

// AgentContains applies the Contains predicate on the "agent" field.
func AgentContains(v string) predicate.ToolUsage {
	return predicate.ToolUsage(sql.FieldContains(FieldAgent, v))
}

// AgentHasPrefix applies the HasPrefix predicate on the "agent" field.
func AgentHasPrefix(v string) predicate.ToolUsage {
	return predicate.ToolUsage(sql.FieldHasPrefix(FieldAgent, v))
}

// AgentHasSuffix applies the HasSuffix predicate on the "agent" field.
func AgentHasSuffix(v string) predicate.ToolUsage {
	return predicate.ToolUsage(sql.FieldHasSuffix(FieldAgent, v))
}

// AgentEqualFold applies the EqualFold predicate on the "agent" field.
func AgentEqualFold(v string) predicate.ToolUsage {
	return predicate.ToolUsage(sql.FieldEqualFold(FieldAgent, v))
}

// AgentContainsFold applies the ContainsFold predicate on the "agent" field.
func AgentContainsFold(v string) predicate.ToolUsage {
	return predicate.ToolUsage(sql.FieldContainsFold(FieldAgent, v))
}

// TeamEQ applies the EQ predicate on the "team" field.
func TeamEQ(v string) predicate.ToolUsage {
	return predicate.ToolUsage(sql.FieldEQ(FieldTeam, v))
}

// TeamNEQ applies the NEQ predicate on the "team" field.
func TeamNEQ(v string) predicate.ToolUsage {
	return predicate.ToolUsage(sql.FieldNEQ(FieldTeam, v))
}

// TeamIn applies the In predicate on the "team" field.
func TeamIn(vs ...string) predicate.ToolUsage {
	return predicate.ToolUsage(sql.FieldIn(FieldTeam, vs...))
}

// TeamNotIn applies the NotIn predicate on the "team" field.
func TeamNotIn(vs ...string) predicate.ToolUsage {
	return predicate.ToolUsage(sql.FieldNotIn(FieldTeam, vs...))
}

// TeamGT applies the GT predicate on the "team" field.
func TeamGT(v string) predicate.ToolUsage {
	return predicate.ToolUsage(sql.FieldGT(FieldTeam, v))
}

// TeamGTE applies the GTE predicate on the "team" field.
func TeamGTE(v string) predicate.ToolUsage {
	return predicate.ToolUsage(sql.FieldGTE(FieldTeam, v))
}

// TeamLT applies the LT predicate on the "team" field.
func TeamLT(v string) predicate.ToolUsage {
	return predicate.ToolUsage(sql.FieldLT(FieldTeam, v))
}

// TeamLTE applies the LTE predicate on the "team" field.
func TeamLTE(v string) predicate.ToolUsage {
	return predicate.ToolUsage(sql.FieldLTE(FieldTeam, v))
}

// TeamContains applies the Contains predicate on the "team" field.
func TeamContains(v string) predicate.ToolUsage {
	return predicate.ToolUsage(sql.FieldContains(FieldTeam, v))
}

// TeamHasPrefix applies the HasPrefix predicate on the "team" field.
func TeamHasPrefix(v string) predicate.ToolUsage {
	return predicate.ToolUsage(sql.FieldHasPrefix(FieldTeam, v))
}

// TeamHasSuffix applies the HasSuffix predicate on the "team" field.
func TeamHasSuffix(v string) predicate.ToolUsage {
	return predicate.ToolUsage(sql.FieldHasSuffix(FieldTeam, v))
}

// TeamEqualFold applies the EqualFold predicate on the "team" field.
func TeamEqualFold(v string) predicate.ToolUsage {
	return predicate.ToolUsage(sql.FieldEqualFold(FieldTeam, v))
}

// TeamContainsFold applies the ContainsFold predicate on the "team" field.
func TeamContainsFold(v string) predicate.ToolUsage {
	return predicate.ToolUsage(sql.FieldContainsFold(FieldTeam, v))
}

// CommandEQ applies the EQ predicate on the "command" field.
func CommandEQ(v string) predicate.ToolUsage {
	return predicate.ToolUsage(sql.FieldEQ(FieldCommand, v))
}

// CommandNEQ applies the NEQ predicate on the "command" field.
func CommandNEQ(v string) predicate.ToolUsage {
	return predicate.ToolUsage(sql.FieldNEQ(FieldCommand, v))
}

// CommandIn applies the In predicate on the "command" field.
func CommandIn(vs ...string) predicate.ToolUsage {
	return predicate.ToolUsage(sql.FieldIn(FieldCommand, vs...))
}

// CommandNotIn applies the NotIn predicate on the "command" field.
func CommandNotIn(vs ...string) predicate.ToolUsage {
	return predicate.ToolUsage(sql.FieldNotIn(FieldCommand, vs...))
}

// CommandGT applies the GT predicate on the "command" field.
func CommandGT(v string) predicate.ToolUsage {
	return predicate.ToolUsage(sql.FieldGT(FieldCommand, v))
}

// CommandGTE applies the GTE predicate on the "command" field.
func CommandGTE(v string) predicate.ToolUsage {
	return predicate.ToolUsage(sql.FieldGTE(FieldCommand, v))
}

// CommandLT applies the LT predicate on the "command" field.
func CommandLT(v string) predicate.ToolUsage {
	return predicate.ToolUsage(sql.FieldLT(FieldCommand, v))
}

// CommandLTE applies the LTE predicate on the "command" field.
func CommandLTE(v string) predicate.ToolUsage {
	return predicate.ToolUsage(sql.FieldLTE(FieldCommand, v))
}

// CommandContains applies the Contains predicate on the "command" field.
func CommandContains(v string) predicate.ToolUsage {
	return predicate.ToolUsage(sql.FieldContains(FieldCommand, v))
}

// CommandHasPrefix applies the HasPrefix predicate on the "command" field.
func CommandHasPrefix(v string) predicate.ToolUsage {
	return predicate.ToolUsage(sql.FieldHasPrefix(FieldCommand, v))
}

// CommandHasSuffix applies the HasSuffix predicate on the "command" field.
func CommandHasSuffix(v string) predicate.ToolUsage {
	return predicate.ToolUsage(sql.FieldHasSuffix(FieldCommand, v))
}

// CommandEqualFold applies the EqualFold predicate on the "command" field.
func CommandEqualFold(v string) predicate.ToolUsage {
	return predicate.ToolUsage(sql.FieldEqualFold(FieldCommand, v))
}

// CommandContainsFold applies the ContainsFold predicate on the "command" field.
func CommandContainsFold(v string) predicate.ToolUsage {
	return predicate.ToolUsage(sql.FieldContainsFold(FieldCommand, v))
}

// SubcommandEQ applies the EQ predicate on the "subcommand" field.
func SubcommandEQ(v string) predicate.ToolUsage {
	return predicate.ToolUsage(sql.FieldEQ(FieldSubcommand, v))
}

// SubcommandNEQ applies the NEQ predicate on the "subcommand" field.
func SubcommandNEQ(v string) predicate.ToolUsage {
	return predicate.ToolUsage(sql.FieldNEQ(FieldSubcommand, v))
}

// SubcommandIn applies the In predicate on the "subcommand" field.
func SubcommandIn(vs ...string) predicate.ToolUsage {
	return predicate.ToolUsage(sql.FieldIn(FieldSubcommand, vs...))
}

// SubcommandNotIn applies the NotIn predicate on the "subcommand" field.
func SubcommandNotIn(vs ...string) predicate.ToolUsage {
	return predicate.ToolUsage(sql.FieldNotIn(FieldSubcommand, vs...))
}

// SubcommandGT applies the GT predicate on the "subcommand" field.
func SubcommandGT(v string) predicate.ToolUsage {
	return predicate.ToolUsage(sql.FieldGT(FieldSubcommand, v))
}

// SubcommandGTE applies the GTE predicate on the "subcommand" field.
func SubcommandGTE(v string) predicate.ToolUsage {
	return predicate.ToolUsage(sql.FieldGTE(FieldSubcommand, v))
}

// SubcommandLT applies the LT predicate on the "subcommand" field.
func SubcommandLT(v string) predicate.ToolUsage {
	return predicate.ToolUsage(sql.FieldLT(FieldSubcommand, v))
}

// SubcommandLTE applies the LTE predicate on the "subcommand" field.
func SubcommandLTE(v string) predicate.ToolUsage {
	return predicate.ToolUsage(sql.FieldLTE(FieldSubcommand, v))
}

// SubcommandContains applies the Contains predicate on the "subcommand" field.
func SubcommandContains(v string) predicate.ToolUsage {
	return predicate.ToolUsage(sql.FieldContains(FieldSubcommand, v))
}

// SubcommandHasPrefix applies the HasPrefix predicate on the "subcommand" field.
func SubcommandHasPrefix(v string) predicate.ToolUsage {
	return predicate.ToolUsage(sql.FieldHasPrefix(FieldSubcommand, v))
}

// SubcommandHasSuffix applies the HasSuffix predicate on the "subcommand" field.
func SubcommandHasSuffix(v string) predicate.ToolUsage {
	return predicate.ToolUsage(sql.FieldHasSuffix(FieldSubcommand, v))
}

// SubcommandEqualFold applies the EqualFold predicate on the "subcommand" field.
func SubcommandEqualFold(v string) predicate.ToolUsage {
	return predicate.ToolUsage(sql.FieldEqualFold(FieldSubcommand, v))
}

// SubcommandContainsFold applies the ContainsFold predicate on the "subcommand" field.
func SubcommandContainsFold(v string) predicate.ToolUsage {
	return predicate.ToolUsage(sql.FieldContainsFold(FieldSubcommand, v))
}

// TargetEQ applies the EQ predicate on the "target" field.
func TargetEQ(v string) predicate.ToolUsage {
	return predicate.ToolUsage(sql.FieldEQ(FieldTarget, v))
}

// TargetNEQ applies the NEQ predicate on the "target" field.
func TargetNEQ(v string) predicate.ToolUsage {
	return predicate.ToolUsage(sql.FieldNEQ(FieldTarget, v))
}

// TargetIn applies the In predicate on the "target" field.
func TargetIn(vs ...string) predicate.ToolUsage {
	return predicate.ToolUsage(sql.FieldIn(FieldTarget, vs...))
}

// TargetNotIn applies the NotIn predicate on the "target" field.
func TargetNotIn(vs ...string) predicate.ToolUsage {
	return predicate.ToolUsage(sql.FieldNotIn(FieldTarget, vs...))
}

// TargetGT applies the GT predicate on the "target" field.
func TargetGT(v string) predicate.ToolUsage {
	return predicate.ToolUsage(sql.FieldGT(FieldTarget, v))
}

// TargetGTE applies the GTE predicate on the "target" field.
func TargetGTE(v string) predicate.ToolUsage {
	return predicate.ToolUsage(sql.FieldGTE(FieldTarget, v))
}

// TargetLT applies the LT predicate on the "target" field.
func TargetLT(v string) predicate.ToolUsage {
	return predicate.ToolUsage(sql.FieldLT(FieldTarget, v))
}

// TargetLTE applies the LTE predicate on the "target" field.
func TargetLTE(v string) predicate.ToolUsage {
	return predicate.ToolUsage(sql.FieldLTE(FieldTarget, v))
}

// TargetContains applies the Contains predicate on the "target" field.
func TargetContains(v string) predicate.ToolUsage {
	return predicate.ToolUsage(sql.FieldContains(FieldTarget, v))
}

// TargetHasPrefix applies the HasPrefix predicate on the "target" field.
func TargetHasPrefix(v string) predicate.ToolUsage {
	return predicate.ToolUsage(sql.FieldHasPrefix(FieldTarget, v))
}

// TargetHasSuffix applies the HasSuffix predicate on the "target" field.
func TargetHasSuffix(v string) predicate.ToolUsage {
	return predicate.ToolUsage(sql.FieldHasSuffix(FieldTarget, v))
}

// TargetIsNil applies the IsNil predicate on the "target" field.
func TargetIsNil() predicate.ToolUsage {
	return predicate.ToolUsage(sql.FieldIsNull(FieldTarget))
}

// TargetNotNil applies the NotNil predicate on the "target" field.
func TargetNotNil() predicate.ToolUsage {
	return predicate.ToolUsage(sql.FieldNotNull(FieldTarget))
}

// TargetEqualFold applies the EqualFold predicate on the "target" field.
func TargetEqualFold(v string) predicate.ToolUsage {
	return predicate.ToolUsage(sql.FieldEqualFold(FieldTarget, v))
}

// TargetContainsFold applies the ContainsFold predicate on the "target" field.
func TargetContainsFold(v string) predicate.ToolUsage {
	return predicate.ToolUsage(sql.FieldContainsFold(FieldTarget, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.ToolUsage {
	return predicate.ToolUsage(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.ToolUsage {
	return predicate.ToolUsage(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.ToolUsage {
	return predicate.ToolUsage(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.ToolUsage {
	return predicate.ToolUsage(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.ToolUsage {
	return predicate.ToolUsage(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.ToolUsage {
	return predicate.ToolUsage(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.ToolUsage {
	return predicate.ToolUsage(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.ToolUsage {
	return predicate.ToolUsage(sql.FieldLTE(FieldCreatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.ToolUsage) predicate.ToolUsage {
	return predicate.ToolUsage(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.ToolUsage) predicate.ToolUsage {
	return predicate.ToolUsage(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.ToolUsage) predicate.ToolUsage {
	return predicate.ToolUsage(sql.NotPredicates(p))
}
