version: "2"
run:
  allow-parallel-runners: true
  timeout: 5m

linters:
  default: none
  enable:
    - copyloopvar
    - dupl
    - errcheck
    - goconst
    - gocyclo
    - govet
    - ineffassign
    - lll
    - misspell
    - nakedret
    - prealloc
    - revive
    - staticcheck
    - unconvert
    - unparam
    - unused

  settings:
    revive:
      rules:
        - name: comment-spacings
        - name: import-shadowing
    gocyclo:
      min-complexity: 15
    lll:
      line-length: 120

  exclusions:
    generated: lax
    rules:
      - linters:
          - lll
          - dupl
        path: ent/*
      - linters:
          - staticcheck
          - unused
        path: ent/*
    paths:
      - ent/
      - third_party$
      - builtin$

formatters:
  enable:
    - gofmt
    - goimports
  exclusions:
    generated: lax
    paths:
      - ent/
      - third_party$
      - builtin$
