// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// AttachmentsColumns holds the columns for the "attachments" table.
	AttachmentsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "filename", Type: field.TypeString},
		{Name: "mime_type", Type: field.TypeString},
		{Name: "size_bytes", Type: field.TypeInt64},
		{Name: "path", Type: field.TypeString},
		{Name: "thumbnail_path", Type: field.TypeString, Nullable: true},
		{Name: "message_attachments", Type: field.TypeUUID},
	}
	// AttachmentsTable holds the schema information for the "attachments" table.
	AttachmentsTable = &schema.Table{
		Name:       "attachments",
		Columns:    AttachmentsColumns,
		PrimaryKey: []*schema.Column{AttachmentsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "attachments_messages_attachments",
				Columns:    []*schema.Column{AttachmentsColumns[6]},
				RefColumns: []*schema.Column{MessagesColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
	}
	// CommentsColumns holds the columns for the "comments" table.
	CommentsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "target", Type: field.TypeString},
		{Name: "author", Type: field.TypeString},
		{Name: "body", Type: field.TypeString, Size: 2147483647},
		{Name: "round", Type: field.TypeInt},
		{Name: "team", Type: field.TypeString},
		{Name: "created_at", Type: field.TypeTime},
	}
	// CommentsTable holds the schema information for the "comments" table.
	CommentsTable = &schema.Table{
		Name:       "comments",
		Columns:    CommentsColumns,
		PrimaryKey: []*schema.Column{CommentsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "comment_target_created_at",
				Unique:  false,
				Columns: []*schema.Column{CommentsColumns[1], CommentsColumns[6]},
			},
			{
				Name:    "comment_team_created_at",
				Unique:  false,
				Columns: []*schema.Column{CommentsColumns[5], CommentsColumns[6]},
			},
		},
	}
	// MessagesColumns holds the columns for the "messages" table.
	MessagesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "sender", Type: field.TypeString},
		{Name: "recipient", Type: field.TypeString},
		{Name: "content", Type: field.TypeString, Size: 2147483647},
		{Name: "message_type", Type: field.TypeEnum, Enums: []string{"text", "system", "notification"}, Default: "text"},
		{Name: "team", Type: field.TypeString},
		{Name: "channel", Type: field.TypeEnum, Enums: []string{"telegram", "matrix", "gui", "cli", "watcher", "adapter"}},
		{Name: "runtime", Type: field.TypeString, Nullable: true},
		{Name: "reply_to_id", Type: field.TypeUUID, Nullable: true},
		{Name: "created_at", Type: field.TypeTime},
	}
	// MessagesTable holds the schema information for the "messages" table.
	MessagesTable = &schema.Table{
		Name:       "messages",
		Columns:    MessagesColumns,
		PrimaryKey: []*schema.Column{MessagesColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "message_sender_recipient_created_at",
				Unique:  false,
				Columns: []*schema.Column{MessagesColumns[1], MessagesColumns[2], MessagesColumns[9]},
			},
			{
				Name:    "message_created_at",
				Unique:  false,
				Columns: []*schema.Column{MessagesColumns[9]},
			},
			{
				Name:    "message_reply_to_id",
				Unique:  false,
				Columns: []*schema.Column{MessagesColumns[8]},
			},
			{
				Name:    "message_team_created_at",
				Unique:  false,
				Columns: []*schema.Column{MessagesColumns[5], MessagesColumns[9]},
			},
		},
	}
	// ReactionsColumns holds the columns for the "reactions" table.
	ReactionsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "emoji", Type: field.TypeString},
		{Name: "from_agent", Type: field.TypeString},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "message_reactions", Type: field.TypeUUID},
	}
	// ReactionsTable holds the schema information for the "reactions" table.
	ReactionsTable = &schema.Table{
		Name:       "reactions",
		Columns:    ReactionsColumns,
		PrimaryKey: []*schema.Column{ReactionsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "reactions_messages_reactions",
				Columns:    []*schema.Column{ReactionsColumns[4]},
				RefColumns: []*schema.Column{MessagesColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "reaction_emoji_from_agent_message_reactions",
				Unique:  true,
				Columns: []*schema.Column{ReactionsColumns[1], ReactionsColumns[2], ReactionsColumns[4]},
			},
		},
	}
	// ToolUsagesColumns holds the columns for the "tool_usages" table.
	ToolUsagesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "agent", Type: field.TypeString},
		{Name: "team", Type: field.TypeString},
		{Name: "command", Type: field.TypeString},
		{Name: "subcommand", Type: field.TypeString},
		{Name: "target", Type: field.TypeString, Nullable: true},
		{Name: "created_at", Type: field.TypeTime},
	}
	// ToolUsagesTable holds the schema information for the "tool_usages" table.
	ToolUsagesTable = &schema.Table{
		Name:       "tool_usages",
		Columns:    ToolUsagesColumns,
		PrimaryKey: []*schema.Column{ToolUsagesColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "toolusage_agent_created_at",
				Unique:  false,
				Columns: []*schema.Column{ToolUsagesColumns[1], ToolUsagesColumns[6]},
			},
			{
				Name:    "toolusage_agent_subcommand_created_at",
				Unique:  false,
				Columns: []*schema.Column{ToolUsagesColumns[1], ToolUsagesColumns[4], ToolUsagesColumns[6]},
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		AttachmentsTable,
		CommentsTable,
		MessagesTable,
		ReactionsTable,
		ToolUsagesTable,
	}
)

func init() {
	AttachmentsTable.ForeignKeys[0].RefTable = MessagesTable
	ReactionsTable.ForeignKeys[0].RefTable = MessagesTable
}
