// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/tta-lab/ttal-cli/internal/ent/message"
	"github.com/tta-lab/ttal-cli/internal/ent/predicate"
	"github.com/tta-lab/ttal-cli/internal/ent/reaction"
)

// ReactionUpdate is the builder for updating Reaction entities.
type ReactionUpdate struct {
	config
	hooks    []Hook
	mutation *ReactionMutation
}

// Where appends a list predicates to the ReactionUpdate builder.
func (_u *ReactionUpdate) Where(ps ...predicate.Reaction) *ReactionUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetEmoji sets the "emoji" field.
func (_u *ReactionUpdate) SetEmoji(v string) *ReactionUpdate {
	_u.mutation.SetEmoji(v)
	return _u
}

// SetNillableEmoji sets the "emoji" field if the given value is not nil.
func (_u *ReactionUpdate) SetNillableEmoji(v *string) *ReactionUpdate {
	if v != nil {
		_u.SetEmoji(*v)
	}
	return _u
}

// SetFromAgent sets the "from_agent" field.
func (_u *ReactionUpdate) SetFromAgent(v string) *ReactionUpdate {
	_u.mutation.SetFromAgent(v)
	return _u
}

// SetNillableFromAgent sets the "from_agent" field if the given value is not nil.
func (_u *ReactionUpdate) SetNillableFromAgent(v *string) *ReactionUpdate {
	if v != nil {
		_u.SetFromAgent(*v)
	}
	return _u
}

// SetMessageID sets the "message" edge to the Message entity by ID.
func (_u *ReactionUpdate) SetMessageID(id uuid.UUID) *ReactionUpdate {
	_u.mutation.SetMessageID(id)
	return _u
}

// SetMessage sets the "message" edge to the Message entity.
func (_u *ReactionUpdate) SetMessage(v *Message) *ReactionUpdate {
	return _u.SetMessageID(v.ID)
}

// Mutation returns the ReactionMutation object of the builder.
func (_u *ReactionUpdate) Mutation() *ReactionMutation {
	return _u.mutation
}

// ClearMessage clears the "message" edge to the Message entity.
func (_u *ReactionUpdate) ClearMessage() *ReactionUpdate {
	_u.mutation.ClearMessage()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ReactionUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ReactionUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ReactionUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ReactionUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ReactionUpdate) check() error {
	if _u.mutation.MessageCleared() && len(_u.mutation.MessageIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Reaction.message"`)
	}
	return nil
}

func (_u *ReactionUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(reaction.Table, reaction.Columns, sqlgraph.NewFieldSpec(reaction.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Emoji(); ok {
		_spec.SetField(reaction.FieldEmoji, field.TypeString, value)
	}
	if value, ok := _u.mutation.FromAgent(); ok {
		_spec.SetField(reaction.FieldFromAgent, field.TypeString, value)
	}
	if _u.mutation.MessageCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   reaction.MessageTable,
			Columns: []string{reaction.MessageColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(message.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.MessageIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   reaction.MessageTable,
			Columns: []string{reaction.MessageColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(message.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{reaction.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ReactionUpdateOne is the builder for updating a single Reaction entity.
type ReactionUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ReactionMutation
}

// SetEmoji sets the "emoji" field.
func (_u *ReactionUpdateOne) SetEmoji(v string) *ReactionUpdateOne {
	_u.mutation.SetEmoji(v)
	return _u
}

// SetNillableEmoji sets the "emoji" field if the given value is not nil.
func (_u *ReactionUpdateOne) SetNillableEmoji(v *string) *ReactionUpdateOne {
	if v != nil {
		_u.SetEmoji(*v)
	}
	return _u
}

// SetFromAgent sets the "from_agent" field.
func (_u *ReactionUpdateOne) SetFromAgent(v string) *ReactionUpdateOne {
	_u.mutation.SetFromAgent(v)
	return _u
}

// SetNillableFromAgent sets the "from_agent" field if the given value is not nil.
func (_u *ReactionUpdateOne) SetNillableFromAgent(v *string) *ReactionUpdateOne {
	if v != nil {
		_u.SetFromAgent(*v)
	}
	return _u
}

// SetMessageID sets the "message" edge to the Message entity by ID.
func (_u *ReactionUpdateOne) SetMessageID(id uuid.UUID) *ReactionUpdateOne {
	_u.mutation.SetMessageID(id)
	return _u
}

// SetMessage sets the "message" edge to the Message entity.
func (_u *ReactionUpdateOne) SetMessage(v *Message) *ReactionUpdateOne {
	return _u.SetMessageID(v.ID)
}

// Mutation returns the ReactionMutation object of the builder.
func (_u *ReactionUpdateOne) Mutation() *ReactionMutation {
	return _u.mutation
}

// ClearMessage clears the "message" edge to the Message entity.
func (_u *ReactionUpdateOne) ClearMessage() *ReactionUpdateOne {
	_u.mutation.ClearMessage()
	return _u
}

// Where appends a list predicates to the ReactionUpdate builder.
func (_u *ReactionUpdateOne) Where(ps ...predicate.Reaction) *ReactionUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ReactionUpdateOne) Select(field string, fields ...string) *ReactionUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Reaction entity.
func (_u *ReactionUpdateOne) Save(ctx context.Context) (*Reaction, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ReactionUpdateOne) SaveX(ctx context.Context) *Reaction {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ReactionUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ReactionUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ReactionUpdateOne) check() error {
	if _u.mutation.MessageCleared() && len(_u.mutation.MessageIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Reaction.message"`)
	}
	return nil
}

func (_u *ReactionUpdateOne) sqlSave(ctx context.Context) (_node *Reaction, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(reaction.Table, reaction.Columns, sqlgraph.NewFieldSpec(reaction.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Reaction.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, reaction.FieldID)
		for _, f := range fields {
			if !reaction.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != reaction.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Emoji(); ok {
		_spec.SetField(reaction.FieldEmoji, field.TypeString, value)
	}
	if value, ok := _u.mutation.FromAgent(); ok {
		_spec.SetField(reaction.FieldFromAgent, field.TypeString, value)
	}
	if _u.mutation.MessageCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   reaction.MessageTable,
			Columns: []string{reaction.MessageColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(message.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.MessageIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   reaction.MessageTable,
			Columns: []string{reaction.MessageColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(message.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Reaction{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{reaction.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
