// Code generated by ent, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/google/uuid"
	"github.com/tta-lab/ttal-cli/internal/ent/attachment"
	"github.com/tta-lab/ttal-cli/internal/ent/comment"
	"github.com/tta-lab/ttal-cli/internal/ent/message"
	"github.com/tta-lab/ttal-cli/internal/ent/reaction"
	"github.com/tta-lab/ttal-cli/internal/ent/schema"
	"github.com/tta-lab/ttal-cli/internal/ent/toolusage"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	attachmentFields := schema.Attachment{}.Fields()
	_ = attachmentFields
	// attachmentDescFilename is the schema descriptor for filename field.
	attachmentDescFilename := attachmentFields[1].Descriptor()
	// attachment.FilenameValidator is a validator for the "filename" field. It is called by the builders before save.
	attachment.FilenameValidator = attachmentDescFilename.Validators[0].(func(string) error)
	// attachmentDescMimeType is the schema descriptor for mime_type field.
	attachmentDescMimeType := attachmentFields[2].Descriptor()
	// attachment.MimeTypeValidator is a validator for the "mime_type" field. It is called by the builders before save.
	attachment.MimeTypeValidator = attachmentDescMimeType.Validators[0].(func(string) error)
	// attachmentDescSizeBytes is the schema descriptor for size_bytes field.
	attachmentDescSizeBytes := attachmentFields[3].Descriptor()
	// attachment.SizeBytesValidator is a validator for the "size_bytes" field. It is called by the builders before save.
	attachment.SizeBytesValidator = attachmentDescSizeBytes.Validators[0].(func(int64) error)
	// attachmentDescPath is the schema descriptor for path field.
	attachmentDescPath := attachmentFields[4].Descriptor()
	// attachment.PathValidator is a validator for the "path" field. It is called by the builders before save.
	attachment.PathValidator = attachmentDescPath.Validators[0].(func(string) error)
	// attachmentDescID is the schema descriptor for id field.
	attachmentDescID := attachmentFields[0].Descriptor()
	// attachment.DefaultID holds the default value on creation for the id field.
	attachment.DefaultID = attachmentDescID.Default.(func() uuid.UUID)
	commentFields := schema.Comment{}.Fields()
	_ = commentFields
	// commentDescTarget is the schema descriptor for target field.
	commentDescTarget := commentFields[1].Descriptor()
	// comment.TargetValidator is a validator for the "target" field. It is called by the builders before save.
	comment.TargetValidator = commentDescTarget.Validators[0].(func(string) error)
	// commentDescAuthor is the schema descriptor for author field.
	commentDescAuthor := commentFields[2].Descriptor()
	// comment.AuthorValidator is a validator for the "author" field. It is called by the builders before save.
	comment.AuthorValidator = commentDescAuthor.Validators[0].(func(string) error)
	// commentDescRound is the schema descriptor for round field.
	commentDescRound := commentFields[4].Descriptor()
	// comment.RoundValidator is a validator for the "round" field. It is called by the builders before save.
	comment.RoundValidator = commentDescRound.Validators[0].(func(int) error)
	// commentDescTeam is the schema descriptor for team field.
	commentDescTeam := commentFields[5].Descriptor()
	// comment.TeamValidator is a validator for the "team" field. It is called by the builders before save.
	comment.TeamValidator = commentDescTeam.Validators[0].(func(string) error)
	// commentDescCreatedAt is the schema descriptor for created_at field.
	commentDescCreatedAt := commentFields[6].Descriptor()
	// comment.DefaultCreatedAt holds the default value on creation for the created_at field.
	comment.DefaultCreatedAt = commentDescCreatedAt.Default.(func() time.Time)
	// commentDescID is the schema descriptor for id field.
	commentDescID := commentFields[0].Descriptor()
	// comment.DefaultID holds the default value on creation for the id field.
	comment.DefaultID = commentDescID.Default.(func() uuid.UUID)
	messageFields := schema.Message{}.Fields()
	_ = messageFields
	// messageDescSender is the schema descriptor for sender field.
	messageDescSender := messageFields[1].Descriptor()
	// message.SenderValidator is a validator for the "sender" field. It is called by the builders before save.
	message.SenderValidator = messageDescSender.Validators[0].(func(string) error)
	// messageDescRecipient is the schema descriptor for recipient field.
	messageDescRecipient := messageFields[2].Descriptor()
	// message.RecipientValidator is a validator for the "recipient" field. It is called by the builders before save.
	message.RecipientValidator = messageDescRecipient.Validators[0].(func(string) error)
	// messageDescTeam is the schema descriptor for team field.
	messageDescTeam := messageFields[5].Descriptor()
	// message.TeamValidator is a validator for the "team" field. It is called by the builders before save.
	message.TeamValidator = messageDescTeam.Validators[0].(func(string) error)
	// messageDescRuntime is the schema descriptor for runtime field.
	messageDescRuntime := messageFields[7].Descriptor()
	// message.RuntimeValidator is a validator for the "runtime" field. It is called by the builders before save.
	message.RuntimeValidator = messageDescRuntime.Validators[0].(func(string) error)
	// messageDescCreatedAt is the schema descriptor for created_at field.
	messageDescCreatedAt := messageFields[9].Descriptor()
	// message.DefaultCreatedAt holds the default value on creation for the created_at field.
	message.DefaultCreatedAt = messageDescCreatedAt.Default.(func() time.Time)
	// messageDescID is the schema descriptor for id field.
	messageDescID := messageFields[0].Descriptor()
	// message.DefaultID holds the default value on creation for the id field.
	message.DefaultID = messageDescID.Default.(func() uuid.UUID)
	reactionFields := schema.Reaction{}.Fields()
	_ = reactionFields
	// reactionDescCreatedAt is the schema descriptor for created_at field.
	reactionDescCreatedAt := reactionFields[3].Descriptor()
	// reaction.DefaultCreatedAt holds the default value on creation for the created_at field.
	reaction.DefaultCreatedAt = reactionDescCreatedAt.Default.(func() time.Time)
	// reactionDescID is the schema descriptor for id field.
	reactionDescID := reactionFields[0].Descriptor()
	// reaction.DefaultID holds the default value on creation for the id field.
	reaction.DefaultID = reactionDescID.Default.(func() uuid.UUID)
	toolusageFields := schema.ToolUsage{}.Fields()
	_ = toolusageFields
	// toolusageDescAgent is the schema descriptor for agent field.
	toolusageDescAgent := toolusageFields[1].Descriptor()
	// toolusage.AgentValidator is a validator for the "agent" field. It is called by the builders before save.
	toolusage.AgentValidator = toolusageDescAgent.Validators[0].(func(string) error)
	// toolusageDescTeam is the schema descriptor for team field.
	toolusageDescTeam := toolusageFields[2].Descriptor()
	// toolusage.TeamValidator is a validator for the "team" field. It is called by the builders before save.
	toolusage.TeamValidator = toolusageDescTeam.Validators[0].(func(string) error)
	// toolusageDescCommand is the schema descriptor for command field.
	toolusageDescCommand := toolusageFields[3].Descriptor()
	// toolusage.CommandValidator is a validator for the "command" field. It is called by the builders before save.
	toolusage.CommandValidator = toolusageDescCommand.Validators[0].(func(string) error)
	// toolusageDescSubcommand is the schema descriptor for subcommand field.
	toolusageDescSubcommand := toolusageFields[4].Descriptor()
	// toolusage.SubcommandValidator is a validator for the "subcommand" field. It is called by the builders before save.
	toolusage.SubcommandValidator = toolusageDescSubcommand.Validators[0].(func(string) error)
	// toolusageDescCreatedAt is the schema descriptor for created_at field.
	toolusageDescCreatedAt := toolusageFields[6].Descriptor()
	// toolusage.DefaultCreatedAt holds the default value on creation for the created_at field.
	toolusage.DefaultCreatedAt = toolusageDescCreatedAt.Default.(func() time.Time)
	// toolusageDescID is the schema descriptor for id field.
	toolusageDescID := toolusageFields[0].Descriptor()
	// toolusage.DefaultID holds the default value on creation for the id field.
	toolusage.DefaultID = toolusageDescID.Default.(func() uuid.UUID)
}
