// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/tta-lab/ttal-cli/internal/ent/toolusage"
)

// ToolUsageCreate is the builder for creating a ToolUsage entity.
type ToolUsageCreate struct {
	config
	mutation *ToolUsageMutation
	hooks    []Hook
}

// SetAgent sets the "agent" field.
func (_c *ToolUsageCreate) SetAgent(v string) *ToolUsageCreate {
	_c.mutation.SetAgent(v)
	return _c
}

// SetTeam sets the "team" field.
func (_c *ToolUsageCreate) SetTeam(v string) *ToolUsageCreate {
	_c.mutation.SetTeam(v)
	return _c
}

// SetCommand sets the "command" field.
func (_c *ToolUsageCreate) SetCommand(v string) *ToolUsageCreate {
	_c.mutation.SetCommand(v)
	return _c
}

// SetSubcommand sets the "subcommand" field.
func (_c *ToolUsageCreate) SetSubcommand(v string) *ToolUsageCreate {
	_c.mutation.SetSubcommand(v)
	return _c
}

// SetTarget sets the "target" field.
func (_c *ToolUsageCreate) SetTarget(v string) *ToolUsageCreate {
	_c.mutation.SetTarget(v)
	return _c
}

// SetNillableTarget sets the "target" field if the given value is not nil.
func (_c *ToolUsageCreate) SetNillableTarget(v *string) *ToolUsageCreate {
	if v != nil {
		_c.SetTarget(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *ToolUsageCreate) SetCreatedAt(v time.Time) *ToolUsageCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *ToolUsageCreate) SetNillableCreatedAt(v *time.Time) *ToolUsageCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *ToolUsageCreate) SetID(v uuid.UUID) *ToolUsageCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *ToolUsageCreate) SetNillableID(v *uuid.UUID) *ToolUsageCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// Mutation returns the ToolUsageMutation object of the builder.
func (_c *ToolUsageCreate) Mutation() *ToolUsageMutation {
	return _c.mutation
}

// Save creates the ToolUsage in the database.
func (_c *ToolUsageCreate) Save(ctx context.Context) (*ToolUsage, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ToolUsageCreate) SaveX(ctx context.Context) *ToolUsage {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ToolUsageCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ToolUsageCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *ToolUsageCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := toolusage.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := toolusage.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *ToolUsageCreate) check() error {
	if _, ok := _c.mutation.Agent(); !ok {
		return &ValidationError{Name: "agent", err: errors.New(`ent: missing required field "ToolUsage.agent"`)}
	}
	if v, ok := _c.mutation.Agent(); ok {
		if err := toolusage.AgentValidator(v); err != nil {
			return &ValidationError{Name: "agent", err: fmt.Errorf(`ent: validator failed for field "ToolUsage.agent": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Team(); !ok {
		return &ValidationError{Name: "team", err: errors.New(`ent: missing required field "ToolUsage.team"`)}
	}
	if v, ok := _c.mutation.Team(); ok {
		if err := toolusage.TeamValidator(v); err != nil {
			return &ValidationError{Name: "team", err: fmt.Errorf(`ent: validator failed for field "ToolUsage.team": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Command(); !ok {
		return &ValidationError{Name: "command", err: errors.New(`ent: missing required field "ToolUsage.command"`)}
	}
	if v, ok := _c.mutation.Command(); ok {
		if err := toolusage.CommandValidator(v); err != nil {
			return &ValidationError{Name: "command", err: fmt.Errorf(`ent: validator failed for field "ToolUsage.command": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Subcommand(); !ok {
		return &ValidationError{Name: "subcommand", err: errors.New(`ent: missing required field "ToolUsage.subcommand"`)}
	}
	if v, ok := _c.mutation.Subcommand(); ok {
		if err := toolusage.SubcommandValidator(v); err != nil {
			return &ValidationError{Name: "subcommand", err: fmt.Errorf(`ent: validator failed for field "ToolUsage.subcommand": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "ToolUsage.created_at"`)}
	}
	return nil
}

func (_c *ToolUsageCreate) sqlSave(ctx context.Context) (*ToolUsage, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ToolUsageCreate) createSpec() (*ToolUsage, *sqlgraph.CreateSpec) {
	var (
		_node = &ToolUsage{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(toolusage.Table, sqlgraph.NewFieldSpec(toolusage.FieldID, field.TypeUUID))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.Agent(); ok {
		_spec.SetField(toolusage.FieldAgent, field.TypeString, value)
		_node.Agent = value
	}
	if value, ok := _c.mutation.Team(); ok {
		_spec.SetField(toolusage.FieldTeam, field.TypeString, value)
		_node.Team = value
	}
	if value, ok := _c.mutation.Command(); ok {
		_spec.SetField(toolusage.FieldCommand, field.TypeString, value)
		_node.Command = value
	}
	if value, ok := _c.mutation.Subcommand(); ok {
		_spec.SetField(toolusage.FieldSubcommand, field.TypeString, value)
		_node.Subcommand = value
	}
	if value, ok := _c.mutation.Target(); ok {
		_spec.SetField(toolusage.FieldTarget, field.TypeString, value)
		_node.Target = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(toolusage.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	return _node, _spec
}

// ToolUsageCreateBulk is the builder for creating many ToolUsage entities in bulk.
type ToolUsageCreateBulk struct {
	config
	err      error
	builders []*ToolUsageCreate
}

// Save creates the ToolUsage entities in the database.
func (_c *ToolUsageCreateBulk) Save(ctx context.Context) ([]*ToolUsage, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*ToolUsage, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ToolUsageMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ToolUsageCreateBulk) SaveX(ctx context.Context) []*ToolUsage {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ToolUsageCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ToolUsageCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
