// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/tta-lab/ttal-cli/internal/ent/predicate"
	"github.com/tta-lab/ttal-cli/internal/ent/toolusage"
)

// ToolUsageDelete is the builder for deleting a ToolUsage entity.
type ToolUsageDelete struct {
	config
	hooks    []Hook
	mutation *ToolUsageMutation
}

// Where appends a list predicates to the ToolUsageDelete builder.
func (_d *ToolUsageDelete) Where(ps ...predicate.ToolUsage) *ToolUsageDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *ToolUsageDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *ToolUsageDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *ToolUsageDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(toolusage.Table, sqlgraph.NewFieldSpec(toolusage.FieldID, field.TypeUUID))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// ToolUsageDeleteOne is the builder for deleting a single ToolUsage entity.
type ToolUsageDeleteOne struct {
	_d *ToolUsageDelete
}

// Where appends a list predicates to the ToolUsageDelete builder.
func (_d *ToolUsageDeleteOne) Where(ps ...predicate.ToolUsage) *ToolUsageDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *ToolUsageDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{toolusage.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *ToolUsageDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
