// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/tta-lab/ttal-cli/internal/ent/predicate"
	"github.com/tta-lab/ttal-cli/internal/ent/toolusage"
)

// ToolUsageUpdate is the builder for updating ToolUsage entities.
type ToolUsageUpdate struct {
	config
	hooks    []Hook
	mutation *ToolUsageMutation
}

// Where appends a list predicates to the ToolUsageUpdate builder.
func (_u *ToolUsageUpdate) Where(ps ...predicate.ToolUsage) *ToolUsageUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetAgent sets the "agent" field.
func (_u *ToolUsageUpdate) SetAgent(v string) *ToolUsageUpdate {
	_u.mutation.SetAgent(v)
	return _u
}

// SetNillableAgent sets the "agent" field if the given value is not nil.
func (_u *ToolUsageUpdate) SetNillableAgent(v *string) *ToolUsageUpdate {
	if v != nil {
		_u.SetAgent(*v)
	}
	return _u
}

// SetTeam sets the "team" field.
func (_u *ToolUsageUpdate) SetTeam(v string) *ToolUsageUpdate {
	_u.mutation.SetTeam(v)
	return _u
}

// SetNillableTeam sets the "team" field if the given value is not nil.
func (_u *ToolUsageUpdate) SetNillableTeam(v *string) *ToolUsageUpdate {
	if v != nil {
		_u.SetTeam(*v)
	}
	return _u
}

// SetCommand sets the "command" field.
func (_u *ToolUsageUpdate) SetCommand(v string) *ToolUsageUpdate {
	_u.mutation.SetCommand(v)
	return _u
}

// SetNillableCommand sets the "command" field if the given value is not nil.
func (_u *ToolUsageUpdate) SetNillableCommand(v *string) *ToolUsageUpdate {
	if v != nil {
		_u.SetCommand(*v)
	}
	return _u
}

// SetSubcommand sets the "subcommand" field.
func (_u *ToolUsageUpdate) SetSubcommand(v string) *ToolUsageUpdate {
	_u.mutation.SetSubcommand(v)
	return _u
}

// SetNillableSubcommand sets the "subcommand" field if the given value is not nil.
func (_u *ToolUsageUpdate) SetNillableSubcommand(v *string) *ToolUsageUpdate {
	if v != nil {
		_u.SetSubcommand(*v)
	}
	return _u
}

// SetTarget sets the "target" field.
func (_u *ToolUsageUpdate) SetTarget(v string) *ToolUsageUpdate {
	_u.mutation.SetTarget(v)
	return _u
}

// SetNillableTarget sets the "target" field if the given value is not nil.
func (_u *ToolUsageUpdate) SetNillableTarget(v *string) *ToolUsageUpdate {
	if v != nil {
		_u.SetTarget(*v)
	}
	return _u
}

// ClearTarget clears the value of the "target" field.
func (_u *ToolUsageUpdate) ClearTarget() *ToolUsageUpdate {
	_u.mutation.ClearTarget()
	return _u
}

// Mutation returns the ToolUsageMutation object of the builder.
func (_u *ToolUsageUpdate) Mutation() *ToolUsageMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ToolUsageUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ToolUsageUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ToolUsageUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ToolUsageUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ToolUsageUpdate) check() error {
	if v, ok := _u.mutation.Agent(); ok {
		if err := toolusage.AgentValidator(v); err != nil {
			return &ValidationError{Name: "agent", err: fmt.Errorf(`ent: validator failed for field "ToolUsage.agent": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Team(); ok {
		if err := toolusage.TeamValidator(v); err != nil {
			return &ValidationError{Name: "team", err: fmt.Errorf(`ent: validator failed for field "ToolUsage.team": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Command(); ok {
		if err := toolusage.CommandValidator(v); err != nil {
			return &ValidationError{Name: "command", err: fmt.Errorf(`ent: validator failed for field "ToolUsage.command": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Subcommand(); ok {
		if err := toolusage.SubcommandValidator(v); err != nil {
			return &ValidationError{Name: "subcommand", err: fmt.Errorf(`ent: validator failed for field "ToolUsage.subcommand": %w`, err)}
		}
	}
	return nil
}

func (_u *ToolUsageUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(toolusage.Table, toolusage.Columns, sqlgraph.NewFieldSpec(toolusage.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Agent(); ok {
		_spec.SetField(toolusage.FieldAgent, field.TypeString, value)
	}
	if value, ok := _u.mutation.Team(); ok {
		_spec.SetField(toolusage.FieldTeam, field.TypeString, value)
	}
	if value, ok := _u.mutation.Command(); ok {
		_spec.SetField(toolusage.FieldCommand, field.TypeString, value)
	}
	if value, ok := _u.mutation.Subcommand(); ok {
		_spec.SetField(toolusage.FieldSubcommand, field.TypeString, value)
	}
	if value, ok := _u.mutation.Target(); ok {
		_spec.SetField(toolusage.FieldTarget, field.TypeString, value)
	}
	if _u.mutation.TargetCleared() {
		_spec.ClearField(toolusage.FieldTarget, field.TypeString)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{toolusage.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ToolUsageUpdateOne is the builder for updating a single ToolUsage entity.
type ToolUsageUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ToolUsageMutation
}

// SetAgent sets the "agent" field.
func (_u *ToolUsageUpdateOne) SetAgent(v string) *ToolUsageUpdateOne {
	_u.mutation.SetAgent(v)
	return _u
}

// SetNillableAgent sets the "agent" field if the given value is not nil.
func (_u *ToolUsageUpdateOne) SetNillableAgent(v *string) *ToolUsageUpdateOne {
	if v != nil {
		_u.SetAgent(*v)
	}
	return _u
}

// SetTeam sets the "team" field.
func (_u *ToolUsageUpdateOne) SetTeam(v string) *ToolUsageUpdateOne {
	_u.mutation.SetTeam(v)
	return _u
}

// SetNillableTeam sets the "team" field if the given value is not nil.
func (_u *ToolUsageUpdateOne) SetNillableTeam(v *string) *ToolUsageUpdateOne {
	if v != nil {
		_u.SetTeam(*v)
	}
	return _u
}

// SetCommand sets the "command" field.
func (_u *ToolUsageUpdateOne) SetCommand(v string) *ToolUsageUpdateOne {
	_u.mutation.SetCommand(v)
	return _u
}

// SetNillableCommand sets the "command" field if the given value is not nil.
func (_u *ToolUsageUpdateOne) SetNillableCommand(v *string) *ToolUsageUpdateOne {
	if v != nil {
		_u.SetCommand(*v)
	}
	return _u
}

// SetSubcommand sets the "subcommand" field.
func (_u *ToolUsageUpdateOne) SetSubcommand(v string) *ToolUsageUpdateOne {
	_u.mutation.SetSubcommand(v)
	return _u
}

// SetNillableSubcommand sets the "subcommand" field if the given value is not nil.
func (_u *ToolUsageUpdateOne) SetNillableSubcommand(v *string) *ToolUsageUpdateOne {
	if v != nil {
		_u.SetSubcommand(*v)
	}
	return _u
}

// SetTarget sets the "target" field.
func (_u *ToolUsageUpdateOne) SetTarget(v string) *ToolUsageUpdateOne {
	_u.mutation.SetTarget(v)
	return _u
}

// SetNillableTarget sets the "target" field if the given value is not nil.
func (_u *ToolUsageUpdateOne) SetNillableTarget(v *string) *ToolUsageUpdateOne {
	if v != nil {
		_u.SetTarget(*v)
	}
	return _u
}

// ClearTarget clears the value of the "target" field.
func (_u *ToolUsageUpdateOne) ClearTarget() *ToolUsageUpdateOne {
	_u.mutation.ClearTarget()
	return _u
}

// Mutation returns the ToolUsageMutation object of the builder.
func (_u *ToolUsageUpdateOne) Mutation() *ToolUsageMutation {
	return _u.mutation
}

// Where appends a list predicates to the ToolUsageUpdate builder.
func (_u *ToolUsageUpdateOne) Where(ps ...predicate.ToolUsage) *ToolUsageUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ToolUsageUpdateOne) Select(field string, fields ...string) *ToolUsageUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated ToolUsage entity.
func (_u *ToolUsageUpdateOne) Save(ctx context.Context) (*ToolUsage, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ToolUsageUpdateOne) SaveX(ctx context.Context) *ToolUsage {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ToolUsageUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ToolUsageUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ToolUsageUpdateOne) check() error {
	if v, ok := _u.mutation.Agent(); ok {
		if err := toolusage.AgentValidator(v); err != nil {
			return &ValidationError{Name: "agent", err: fmt.Errorf(`ent: validator failed for field "ToolUsage.agent": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Team(); ok {
		if err := toolusage.TeamValidator(v); err != nil {
			return &ValidationError{Name: "team", err: fmt.Errorf(`ent: validator failed for field "ToolUsage.team": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Command(); ok {
		if err := toolusage.CommandValidator(v); err != nil {
			return &ValidationError{Name: "command", err: fmt.Errorf(`ent: validator failed for field "ToolUsage.command": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Subcommand(); ok {
		if err := toolusage.SubcommandValidator(v); err != nil {
			return &ValidationError{Name: "subcommand", err: fmt.Errorf(`ent: validator failed for field "ToolUsage.subcommand": %w`, err)}
		}
	}
	return nil
}

func (_u *ToolUsageUpdateOne) sqlSave(ctx context.Context) (_node *ToolUsage, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(toolusage.Table, toolusage.Columns, sqlgraph.NewFieldSpec(toolusage.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "ToolUsage.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, toolusage.FieldID)
		for _, f := range fields {
			if !toolusage.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != toolusage.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Agent(); ok {
		_spec.SetField(toolusage.FieldAgent, field.TypeString, value)
	}
	if value, ok := _u.mutation.Team(); ok {
		_spec.SetField(toolusage.FieldTeam, field.TypeString, value)
	}
	if value, ok := _u.mutation.Command(); ok {
		_spec.SetField(toolusage.FieldCommand, field.TypeString, value)
	}
	if value, ok := _u.mutation.Subcommand(); ok {
		_spec.SetField(toolusage.FieldSubcommand, field.TypeString, value)
	}
	if value, ok := _u.mutation.Target(); ok {
		_spec.SetField(toolusage.FieldTarget, field.TypeString, value)
	}
	if _u.mutation.TargetCleared() {
		_spec.ClearField(toolusage.FieldTarget, field.TypeString)
	}
	_node = &ToolUsage{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{toolusage.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
