// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Attachment is the predicate function for attachment builders.
type Attachment func(*sql.Selector)

// Comment is the predicate function for comment builders.
type Comment func(*sql.Selector)

// Message is the predicate function for message builders.
type Message func(*sql.Selector)

// Reaction is the predicate function for reaction builders.
type Reaction func(*sql.Selector)

// ToolUsage is the predicate function for toolusage builders.
type ToolUsage func(*sql.Selector)
