// Code generated by ent, DO NOT EDIT.

package message

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
	"github.com/tta-lab/ttal-cli/internal/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.Message {
	return predicate.Message(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.Message {
	return predicate.Message(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.Message {
	return predicate.Message(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.Message {
	return predicate.Message(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.Message {
	return predicate.Message(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.Message {
	return predicate.Message(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.Message {
	return predicate.Message(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.Message {
	return predicate.Message(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.Message {
	return predicate.Message(sql.FieldLTE(FieldID, id))
}

// Sender applies equality check predicate on the "sender" field. It's identical to SenderEQ.
func Sender(v string) predicate.Message {
	return predicate.Message(sql.FieldEQ(FieldSender, v))
}

// Recipient applies equality check predicate on the "recipient" field. It's identical to RecipientEQ.
func Recipient(v string) predicate.Message {
	return predicate.Message(sql.FieldEQ(FieldRecipient, v))
}

// Content applies equality check predicate on the "content" field. It's identical to ContentEQ.
func Content(v string) predicate.Message {
	return predicate.Message(sql.FieldEQ(FieldContent, v))
}

// Team applies equality check predicate on the "team" field. It's identical to TeamEQ.
func Team(v string) predicate.Message {
	return predicate.Message(sql.FieldEQ(FieldTeam, v))
}

// Runtime applies equality check predicate on the "runtime" field. It's identical to RuntimeEQ.
func Runtime(v string) predicate.Message {
	return predicate.Message(sql.FieldEQ(FieldRuntime, v))
}

// ReplyToID applies equality check predicate on the "reply_to_id" field. It's identical to ReplyToIDEQ.
func ReplyToID(v uuid.UUID) predicate.Message {
	return predicate.Message(sql.FieldEQ(FieldReplyToID, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.Message {
	return predicate.Message(sql.FieldEQ(FieldCreatedAt, v))
}

// SenderEQ applies the EQ predicate on the "sender" field.
func SenderEQ(v string) predicate.Message {
	return predicate.Message(sql.FieldEQ(FieldSender, v))
}

// SenderNEQ applies the NEQ predicate on the "sender" field.
func SenderNEQ(v string) predicate.Message {
	return predicate.Message(sql.FieldNEQ(FieldSender, v))
}

// SenderIn applies the In predicate on the "sender" field.
func SenderIn(vs ...string) predicate.Message {
	return predicate.Message(sql.FieldIn(FieldSender, vs...))
}

// SenderNotIn applies the NotIn predicate on the "sender" field.
func SenderNotIn(vs ...string) predicate.Message {
	return predicate.Message(sql.FieldNotIn(FieldSender, vs...))
}

// SenderGT applies the GT predicate on the "sender" field.
func SenderGT(v string) predicate.Message {
	return predicate.Message(sql.FieldGT(FieldSender, v))
}

// SenderGTE applies the GTE predicate on the "sender" field.
func SenderGTE(v string) predicate.Message {
	return predicate.Message(sql.FieldGTE(FieldSender, v))
}

// SenderLT applies the LT predicate on the "sender" field.
func SenderLT(v string) predicate.Message {
	return predicate.Message(sql.FieldLT(FieldSender, v))
}

// SenderLTE applies the LTE predicate on the "sender" field.
func SenderLTE(v string) predicate.Message {
	return predicate.Message(sql.FieldLTE(FieldSender, v))
}

// SenderContains applies the Contains predicate on the "sender" field.
func SenderContains(v string) predicate.Message {
	return predicate.Message(sql.FieldContains(FieldSender, v))
}

// SenderHasPrefix applies the HasPrefix predicate on the "sender" field.
func SenderHasPrefix(v string) predicate.Message {
	return predicate.Message(sql.FieldHasPrefix(FieldSender, v))
}

// SenderHasSuffix applies the HasSuffix predicate on the "sender" field.
func SenderHasSuffix(v string) predicate.Message {
	return predicate.Message(sql.FieldHasSuffix(FieldSender, v))
}

// SenderEqualFold applies the EqualFold predicate on the "sender" field.
func SenderEqualFold(v string) predicate.Message {
	return predicate.Message(sql.FieldEqualFold(FieldSender, v))
}

// SenderContainsFold applies the ContainsFold predicate on the "sender" field.
func SenderContainsFold(v string) predicate.Message {
	return predicate.Message(sql.FieldContainsFold(FieldSender, v))
}

// RecipientEQ applies the EQ predicate on the "recipient" field.
func RecipientEQ(v string) predicate.Message {
	return predicate.Message(sql.FieldEQ(FieldRecipient, v))
}

// RecipientNEQ applies the NEQ predicate on the "recipient" field.
func RecipientNEQ(v string) predicate.Message {
	return predicate.Message(sql.FieldNEQ(FieldRecipient, v))
}

// RecipientIn applies the In predicate on the "recipient" field.
func RecipientIn(vs ...string) predicate.Message {
	return predicate.Message(sql.FieldIn(FieldRecipient, vs...))
}

// RecipientNotIn applies the NotIn predicate on the "recipient" field.
func RecipientNotIn(vs ...string) predicate.Message {
	return predicate.Message(sql.FieldNotIn(FieldRecipient, vs...))
}

// RecipientGT applies the GT predicate on the "recipient" field.
func RecipientGT(v string) predicate.Message {
	return predicate.Message(sql.FieldGT(FieldRecipient, v))
}

// RecipientGTE applies the GTE predicate on the "recipient" field.
func RecipientGTE(v string) predicate.Message {
	return predicate.Message(sql.FieldGTE(FieldRecipient, v))
}

// RecipientLT applies the LT predicate on the "recipient" field.
func RecipientLT(v string) predicate.Message {
	return predicate.Message(sql.FieldLT(FieldRecipient, v))
}

// RecipientLTE applies the LTE predicate on the "recipient" field.
func RecipientLTE(v string) predicate.Message {
	return predicate.Message(sql.FieldLTE(FieldRecipient, v))
}

// RecipientContains applies the Contains predicate on the "recipient" field.
func RecipientContains(v string) predicate.Message {
	return predicate.Message(sql.FieldContains(FieldRecipient, v))
}

// RecipientHasPrefix applies the HasPrefix predicate on the "recipient" field.
func RecipientHasPrefix(v string) predicate.Message {
	return predicate.Message(sql.FieldHasPrefix(FieldRecipient, v))
}

// RecipientHasSuffix applies the HasSuffix predicate on the "recipient" field.
func RecipientHasSuffix(v string) predicate.Message {
	return predicate.Message(sql.FieldHasSuffix(FieldRecipient, v))
}

// RecipientEqualFold applies the EqualFold predicate on the "recipient" field.
func RecipientEqualFold(v string) predicate.Message {
	return predicate.Message(sql.FieldEqualFold(FieldRecipient, v))
}

// RecipientContainsFold applies the ContainsFold predicate on the "recipient" field.
func RecipientContainsFold(v string) predicate.Message {
	return predicate.Message(sql.FieldContainsFold(FieldRecipient, v))
}

// ContentEQ applies the EQ predicate on the "content" field.
func ContentEQ(v string) predicate.Message {
	return predicate.Message(sql.FieldEQ(FieldContent, v))
}

// ContentNEQ applies the NEQ predicate on the "content" field.
func ContentNEQ(v string) predicate.Message {
	return predicate.Message(sql.FieldNEQ(FieldContent, v))
}

// ContentIn applies the In predicate on the "content" field.
func ContentIn(vs ...string) predicate.Message {
	return predicate.Message(sql.FieldIn(FieldContent, vs...))
}

// ContentNotIn applies the NotIn predicate on the "content" field.
func ContentNotIn(vs ...string) predicate.Message {
	return predicate.Message(sql.FieldNotIn(FieldContent, vs...))
}

// ContentGT applies the GT predicate on the "content" field.
func ContentGT(v string) predicate.Message {
	return predicate.Message(sql.FieldGT(FieldContent, v))
}

// ContentGTE applies the GTE predicate on the "content" field.
func ContentGTE(v string) predicate.Message {
	return predicate.Message(sql.FieldGTE(FieldContent, v))
}

// ContentLT applies the LT predicate on the "content" field.
func ContentLT(v string) predicate.Message {
	return predicate.Message(sql.FieldLT(FieldContent, v))
}

// ContentLTE applies the LTE predicate on the "content" field.
func ContentLTE(v string) predicate.Message {
	return predicate.Message(sql.FieldLTE(FieldContent, v))
}

// ContentContains applies the Contains predicate on the "content" field.
func ContentContains(v string) predicate.Message {
	return predicate.Message(sql.FieldContains(FieldContent, v))
}

// ContentHasPrefix applies the HasPrefix predicate on the "content" field.
func ContentHasPrefix(v string) predicate.Message {
	return predicate.Message(sql.FieldHasPrefix(FieldContent, v))
}

// ContentHasSuffix applies the HasSuffix predicate on the "content" field.
func ContentHasSuffix(v string) predicate.Message {
	return predicate.Message(sql.FieldHasSuffix(FieldContent, v))
}

// ContentEqualFold applies the EqualFold predicate on the "content" field.
func ContentEqualFold(v string) predicate.Message {
	return predicate.Message(sql.FieldEqualFold(FieldContent, v))
}

// ContentContainsFold applies the ContainsFold predicate on the "content" field.
func ContentContainsFold(v string) predicate.Message {
	return predicate.Message(sql.FieldContainsFold(FieldContent, v))
}

// MessageTypeEQ applies the EQ predicate on the "message_type" field.
func MessageTypeEQ(v MessageType) predicate.Message {
	return predicate.Message(sql.FieldEQ(FieldMessageType, v))
}

// MessageTypeNEQ applies the NEQ predicate on the "message_type" field.
func MessageTypeNEQ(v MessageType) predicate.Message {
	return predicate.Message(sql.FieldNEQ(FieldMessageType, v))
}

// MessageTypeIn applies the In predicate on the "message_type" field.
func MessageTypeIn(vs ...MessageType) predicate.Message {
	return predicate.Message(sql.FieldIn(FieldMessageType, vs...))
}

// MessageTypeNotIn applies the NotIn predicate on the "message_type" field.
func MessageTypeNotIn(vs ...MessageType) predicate.Message {
	return predicate.Message(sql.FieldNotIn(FieldMessageType, vs...))
}

// TeamEQ applies the EQ predicate on the "team" field.
func TeamEQ(v string) predicate.Message {
	return predicate.Message(sql.FieldEQ(FieldTeam, v))
}

// TeamNEQ applies the NEQ predicate on the "team" field.
func TeamNEQ(v string) predicate.Message {
	return predicate.Message(sql.FieldNEQ(FieldTeam, v))
}

// TeamIn applies the In predicate on the "team" field.
func TeamIn(vs ...string) predicate.Message {
	return predicate.Message(sql.FieldIn(FieldTeam, vs...))
}

// TeamNotIn applies the NotIn predicate on the "team" field.
func TeamNotIn(vs ...string) predicate.Message {
	return predicate.Message(sql.FieldNotIn(FieldTeam, vs...))
}

// TeamGT applies the GT predicate on the "team" field.
func TeamGT(v string) predicate.Message {
	return predicate.Message(sql.FieldGT(FieldTeam, v))
}

// TeamGTE applies the GTE predicate on the "team" field.
func TeamGTE(v string) predicate.Message {
	return predicate.Message(sql.FieldGTE(FieldTeam, v))
}

// TeamLT applies the LT predicate on the "team" field.
func TeamLT(v string) predicate.Message {
	return predicate.Message(sql.FieldLT(FieldTeam, v))
}

// TeamLTE applies the LTE predicate on the "team" field.
func TeamLTE(v string) predicate.Message {
	return predicate.Message(sql.FieldLTE(FieldTeam, v))
}

// TeamContains applies the Contains predicate on the "team" field.
func TeamContains(v string) predicate.Message {
	return predicate.Message(sql.FieldContains(FieldTeam, v))
}

// TeamHasPrefix applies the HasPrefix predicate on the "team" field.
func TeamHasPrefix(v string) predicate.Message {
	return predicate.Message(sql.FieldHasPrefix(FieldTeam, v))
}

// TeamHasSuffix applies the HasSuffix predicate on the "team" field.
func TeamHasSuffix(v string) predicate.Message {
	return predicate.Message(sql.FieldHasSuffix(FieldTeam, v))
}

// TeamEqualFold applies the EqualFold predicate on the "team" field.
func TeamEqualFold(v string) predicate.Message {
	return predicate.Message(sql.FieldEqualFold(FieldTeam, v))
}

// TeamContainsFold applies the ContainsFold predicate on the "team" field.
func TeamContainsFold(v string) predicate.Message {
	return predicate.Message(sql.FieldContainsFold(FieldTeam, v))
}

// ChannelEQ applies the EQ predicate on the "channel" field.
func ChannelEQ(v Channel) predicate.Message {
	return predicate.Message(sql.FieldEQ(FieldChannel, v))
}

// ChannelNEQ applies the NEQ predicate on the "channel" field.
func ChannelNEQ(v Channel) predicate.Message {
	return predicate.Message(sql.FieldNEQ(FieldChannel, v))
}

// ChannelIn applies the In predicate on the "channel" field.
func ChannelIn(vs ...Channel) predicate.Message {
	return predicate.Message(sql.FieldIn(FieldChannel, vs...))
}

// ChannelNotIn applies the NotIn predicate on the "channel" field.
func ChannelNotIn(vs ...Channel) predicate.Message {
	return predicate.Message(sql.FieldNotIn(FieldChannel, vs...))
}

// RuntimeEQ applies the EQ predicate on the "runtime" field.
func RuntimeEQ(v string) predicate.Message {
	return predicate.Message(sql.FieldEQ(FieldRuntime, v))
}

// RuntimeNEQ applies the NEQ predicate on the "runtime" field.
func RuntimeNEQ(v string) predicate.Message {
	return predicate.Message(sql.FieldNEQ(FieldRuntime, v))
}

// RuntimeIn applies the In predicate on the "runtime" field.
func RuntimeIn(vs ...string) predicate.Message {
	return predicate.Message(sql.FieldIn(FieldRuntime, vs...))
}

// RuntimeNotIn applies the NotIn predicate on the "runtime" field.
func RuntimeNotIn(vs ...string) predicate.Message {
	return predicate.Message(sql.FieldNotIn(FieldRuntime, vs...))
}

// RuntimeGT applies the GT predicate on the "runtime" field.
func RuntimeGT(v string) predicate.Message {
	return predicate.Message(sql.FieldGT(FieldRuntime, v))
}

// RuntimeGTE applies the GTE predicate on the "runtime" field.
func RuntimeGTE(v string) predicate.Message {
	return predicate.Message(sql.FieldGTE(FieldRuntime, v))
}

// RuntimeLT applies the LT predicate on the "runtime" field.
func RuntimeLT(v string) predicate.Message {
	return predicate.Message(sql.FieldLT(FieldRuntime, v))
}

// RuntimeLTE applies the LTE predicate on the "runtime" field.
func RuntimeLTE(v string) predicate.Message {
	return predicate.Message(sql.FieldLTE(FieldRuntime, v))
}

// RuntimeContains applies the Contains predicate on the "runtime" field.
func RuntimeContains(v string) predicate.Message {
	return predicate.Message(sql.FieldContains(FieldRuntime, v))
}

// RuntimeHasPrefix applies the HasPrefix predicate on the "runtime" field.
func RuntimeHasPrefix(v string) predicate.Message {
	return predicate.Message(sql.FieldHasPrefix(FieldRuntime, v))
}

// RuntimeHasSuffix applies the HasSuffix predicate on the "runtime" field.
func RuntimeHasSuffix(v string) predicate.Message {
	return predicate.Message(sql.FieldHasSuffix(FieldRuntime, v))
}

// RuntimeIsNil applies the IsNil predicate on the "runtime" field.
func RuntimeIsNil() predicate.Message {
	return predicate.Message(sql.FieldIsNull(FieldRuntime))
}

// RuntimeNotNil applies the NotNil predicate on the "runtime" field.
func RuntimeNotNil() predicate.Message {
	return predicate.Message(sql.FieldNotNull(FieldRuntime))
}

// RuntimeEqualFold applies the EqualFold predicate on the "runtime" field.
func RuntimeEqualFold(v string) predicate.Message {
	return predicate.Message(sql.FieldEqualFold(FieldRuntime, v))
}

// RuntimeContainsFold applies the ContainsFold predicate on the "runtime" field.
func RuntimeContainsFold(v string) predicate.Message {
	return predicate.Message(sql.FieldContainsFold(FieldRuntime, v))
}

// ReplyToIDEQ applies the EQ predicate on the "reply_to_id" field.
func ReplyToIDEQ(v uuid.UUID) predicate.Message {
	return predicate.Message(sql.FieldEQ(FieldReplyToID, v))
}

// ReplyToIDNEQ applies the NEQ predicate on the "reply_to_id" field.
func ReplyToIDNEQ(v uuid.UUID) predicate.Message {
	return predicate.Message(sql.FieldNEQ(FieldReplyToID, v))
}

// ReplyToIDIn applies the In predicate on the "reply_to_id" field.
func ReplyToIDIn(vs ...uuid.UUID) predicate.Message {
	return predicate.Message(sql.FieldIn(FieldReplyToID, vs...))
}

// ReplyToIDNotIn applies the NotIn predicate on the "reply_to_id" field.
func ReplyToIDNotIn(vs ...uuid.UUID) predicate.Message {
	return predicate.Message(sql.FieldNotIn(FieldReplyToID, vs...))
}

// ReplyToIDGT applies the GT predicate on the "reply_to_id" field.
func ReplyToIDGT(v uuid.UUID) predicate.Message {
	return predicate.Message(sql.FieldGT(FieldReplyToID, v))
}

// ReplyToIDGTE applies the GTE predicate on the "reply_to_id" field.
func ReplyToIDGTE(v uuid.UUID) predicate.Message {
	return predicate.Message(sql.FieldGTE(FieldReplyToID, v))
}

// ReplyToIDLT applies the LT predicate on the "reply_to_id" field.
func ReplyToIDLT(v uuid.UUID) predicate.Message {
	return predicate.Message(sql.FieldLT(FieldReplyToID, v))
}

// ReplyToIDLTE applies the LTE predicate on the "reply_to_id" field.
func ReplyToIDLTE(v uuid.UUID) predicate.Message {
	return predicate.Message(sql.FieldLTE(FieldReplyToID, v))
}

// ReplyToIDIsNil applies the IsNil predicate on the "reply_to_id" field.
func ReplyToIDIsNil() predicate.Message {
	return predicate.Message(sql.FieldIsNull(FieldReplyToID))
}

// ReplyToIDNotNil applies the NotNil predicate on the "reply_to_id" field.
func ReplyToIDNotNil() predicate.Message {
	return predicate.Message(sql.FieldNotNull(FieldReplyToID))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.Message {
	return predicate.Message(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.Message {
	return predicate.Message(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.Message {
	return predicate.Message(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.Message {
	return predicate.Message(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.Message {
	return predicate.Message(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.Message {
	return predicate.Message(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.Message {
	return predicate.Message(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.Message {
	return predicate.Message(sql.FieldLTE(FieldCreatedAt, v))
}

// HasAttachments applies the HasEdge predicate on the "attachments" edge.
func HasAttachments() predicate.Message {
	return predicate.Message(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, AttachmentsTable, AttachmentsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasAttachmentsWith applies the HasEdge predicate on the "attachments" edge with a given conditions (other predicates).
func HasAttachmentsWith(preds ...predicate.Attachment) predicate.Message {
	return predicate.Message(func(s *sql.Selector) {
		step := newAttachmentsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasReactions applies the HasEdge predicate on the "reactions" edge.
func HasReactions() predicate.Message {
	return predicate.Message(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, ReactionsTable, ReactionsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasReactionsWith applies the HasEdge predicate on the "reactions" edge with a given conditions (other predicates).
func HasReactionsWith(preds ...predicate.Reaction) predicate.Message {
	return predicate.Message(func(s *sql.Selector) {
		step := newReactionsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Message) predicate.Message {
	return predicate.Message(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Message) predicate.Message {
	return predicate.Message(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Message) predicate.Message {
	return predicate.Message(sql.NotPredicates(p))
}
