// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

import * as $models from "./models.js";

/**
 * A UUID is a 128 bit (16 byte) Universal Unique IDentifier as defined in RFC
 * 4122.
 * @typedef {$models.UUID} UUID
 */
