// Code generated by ent, DO NOT EDIT.

package agent

import (
	"time"

	"codeberg.org/clawteam/ttal-cli/ent/predicate"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.Agent {
	return predicate.Agent(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.Agent {
	return predicate.Agent(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.Agent {
	return predicate.Agent(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.Agent {
	return predicate.Agent(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.Agent {
	return predicate.Agent(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.Agent {
	return predicate.Agent(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.Agent {
	return predicate.Agent(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.Agent {
	return predicate.Agent(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.Agent {
	return predicate.Agent(sql.FieldLTE(FieldID, id))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.Agent {
	return predicate.Agent(sql.FieldEQ(FieldName, v))
}

// Path applies equality check predicate on the "path" field. It's identical to PathEQ.
func Path(v string) predicate.Agent {
	return predicate.Agent(sql.FieldEQ(FieldPath, v))
}

// Voice applies equality check predicate on the "voice" field. It's identical to VoiceEQ.
func Voice(v string) predicate.Agent {
	return predicate.Agent(sql.FieldEQ(FieldVoice, v))
}

// Emoji applies equality check predicate on the "emoji" field. It's identical to EmojiEQ.
func Emoji(v string) predicate.Agent {
	return predicate.Agent(sql.FieldEQ(FieldEmoji, v))
}

// Description applies equality check predicate on the "description" field. It's identical to DescriptionEQ.
func Description(v string) predicate.Agent {
	return predicate.Agent(sql.FieldEQ(FieldDescription, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.Agent {
	return predicate.Agent(sql.FieldEQ(FieldCreatedAt, v))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.Agent {
	return predicate.Agent(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.Agent {
	return predicate.Agent(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.Agent {
	return predicate.Agent(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.Agent {
	return predicate.Agent(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.Agent {
	return predicate.Agent(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.Agent {
	return predicate.Agent(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.Agent {
	return predicate.Agent(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.Agent {
	return predicate.Agent(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.Agent {
	return predicate.Agent(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.Agent {
	return predicate.Agent(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.Agent {
	return predicate.Agent(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.Agent {
	return predicate.Agent(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.Agent {
	return predicate.Agent(sql.FieldContainsFold(FieldName, v))
}

// PathEQ applies the EQ predicate on the "path" field.
func PathEQ(v string) predicate.Agent {
	return predicate.Agent(sql.FieldEQ(FieldPath, v))
}

// PathNEQ applies the NEQ predicate on the "path" field.
func PathNEQ(v string) predicate.Agent {
	return predicate.Agent(sql.FieldNEQ(FieldPath, v))
}

// PathIn applies the In predicate on the "path" field.
func PathIn(vs ...string) predicate.Agent {
	return predicate.Agent(sql.FieldIn(FieldPath, vs...))
}

// PathNotIn applies the NotIn predicate on the "path" field.
func PathNotIn(vs ...string) predicate.Agent {
	return predicate.Agent(sql.FieldNotIn(FieldPath, vs...))
}

// PathGT applies the GT predicate on the "path" field.
func PathGT(v string) predicate.Agent {
	return predicate.Agent(sql.FieldGT(FieldPath, v))
}

// PathGTE applies the GTE predicate on the "path" field.
func PathGTE(v string) predicate.Agent {
	return predicate.Agent(sql.FieldGTE(FieldPath, v))
}

// PathLT applies the LT predicate on the "path" field.
func PathLT(v string) predicate.Agent {
	return predicate.Agent(sql.FieldLT(FieldPath, v))
}

// PathLTE applies the LTE predicate on the "path" field.
func PathLTE(v string) predicate.Agent {
	return predicate.Agent(sql.FieldLTE(FieldPath, v))
}

// PathContains applies the Contains predicate on the "path" field.
func PathContains(v string) predicate.Agent {
	return predicate.Agent(sql.FieldContains(FieldPath, v))
}

// PathHasPrefix applies the HasPrefix predicate on the "path" field.
func PathHasPrefix(v string) predicate.Agent {
	return predicate.Agent(sql.FieldHasPrefix(FieldPath, v))
}

// PathHasSuffix applies the HasSuffix predicate on the "path" field.
func PathHasSuffix(v string) predicate.Agent {
	return predicate.Agent(sql.FieldHasSuffix(FieldPath, v))
}

// PathIsNil applies the IsNil predicate on the "path" field.
func PathIsNil() predicate.Agent {
	return predicate.Agent(sql.FieldIsNull(FieldPath))
}

// PathNotNil applies the NotNil predicate on the "path" field.
func PathNotNil() predicate.Agent {
	return predicate.Agent(sql.FieldNotNull(FieldPath))
}

// PathEqualFold applies the EqualFold predicate on the "path" field.
func PathEqualFold(v string) predicate.Agent {
	return predicate.Agent(sql.FieldEqualFold(FieldPath, v))
}

// PathContainsFold applies the ContainsFold predicate on the "path" field.
func PathContainsFold(v string) predicate.Agent {
	return predicate.Agent(sql.FieldContainsFold(FieldPath, v))
}

// VoiceEQ applies the EQ predicate on the "voice" field.
func VoiceEQ(v string) predicate.Agent {
	return predicate.Agent(sql.FieldEQ(FieldVoice, v))
}

// VoiceNEQ applies the NEQ predicate on the "voice" field.
func VoiceNEQ(v string) predicate.Agent {
	return predicate.Agent(sql.FieldNEQ(FieldVoice, v))
}

// VoiceIn applies the In predicate on the "voice" field.
func VoiceIn(vs ...string) predicate.Agent {
	return predicate.Agent(sql.FieldIn(FieldVoice, vs...))
}

// VoiceNotIn applies the NotIn predicate on the "voice" field.
func VoiceNotIn(vs ...string) predicate.Agent {
	return predicate.Agent(sql.FieldNotIn(FieldVoice, vs...))
}

// VoiceGT applies the GT predicate on the "voice" field.
func VoiceGT(v string) predicate.Agent {
	return predicate.Agent(sql.FieldGT(FieldVoice, v))
}

// VoiceGTE applies the GTE predicate on the "voice" field.
func VoiceGTE(v string) predicate.Agent {
	return predicate.Agent(sql.FieldGTE(FieldVoice, v))
}

// VoiceLT applies the LT predicate on the "voice" field.
func VoiceLT(v string) predicate.Agent {
	return predicate.Agent(sql.FieldLT(FieldVoice, v))
}

// VoiceLTE applies the LTE predicate on the "voice" field.
func VoiceLTE(v string) predicate.Agent {
	return predicate.Agent(sql.FieldLTE(FieldVoice, v))
}

// VoiceContains applies the Contains predicate on the "voice" field.
func VoiceContains(v string) predicate.Agent {
	return predicate.Agent(sql.FieldContains(FieldVoice, v))
}

// VoiceHasPrefix applies the HasPrefix predicate on the "voice" field.
func VoiceHasPrefix(v string) predicate.Agent {
	return predicate.Agent(sql.FieldHasPrefix(FieldVoice, v))
}

// VoiceHasSuffix applies the HasSuffix predicate on the "voice" field.
func VoiceHasSuffix(v string) predicate.Agent {
	return predicate.Agent(sql.FieldHasSuffix(FieldVoice, v))
}

// VoiceIsNil applies the IsNil predicate on the "voice" field.
func VoiceIsNil() predicate.Agent {
	return predicate.Agent(sql.FieldIsNull(FieldVoice))
}

// VoiceNotNil applies the NotNil predicate on the "voice" field.
func VoiceNotNil() predicate.Agent {
	return predicate.Agent(sql.FieldNotNull(FieldVoice))
}

// VoiceEqualFold applies the EqualFold predicate on the "voice" field.
func VoiceEqualFold(v string) predicate.Agent {
	return predicate.Agent(sql.FieldEqualFold(FieldVoice, v))
}

// VoiceContainsFold applies the ContainsFold predicate on the "voice" field.
func VoiceContainsFold(v string) predicate.Agent {
	return predicate.Agent(sql.FieldContainsFold(FieldVoice, v))
}

// EmojiEQ applies the EQ predicate on the "emoji" field.
func EmojiEQ(v string) predicate.Agent {
	return predicate.Agent(sql.FieldEQ(FieldEmoji, v))
}

// EmojiNEQ applies the NEQ predicate on the "emoji" field.
func EmojiNEQ(v string) predicate.Agent {
	return predicate.Agent(sql.FieldNEQ(FieldEmoji, v))
}

// EmojiIn applies the In predicate on the "emoji" field.
func EmojiIn(vs ...string) predicate.Agent {
	return predicate.Agent(sql.FieldIn(FieldEmoji, vs...))
}

// EmojiNotIn applies the NotIn predicate on the "emoji" field.
func EmojiNotIn(vs ...string) predicate.Agent {
	return predicate.Agent(sql.FieldNotIn(FieldEmoji, vs...))
}

// EmojiGT applies the GT predicate on the "emoji" field.
func EmojiGT(v string) predicate.Agent {
	return predicate.Agent(sql.FieldGT(FieldEmoji, v))
}

// EmojiGTE applies the GTE predicate on the "emoji" field.
func EmojiGTE(v string) predicate.Agent {
	return predicate.Agent(sql.FieldGTE(FieldEmoji, v))
}

// EmojiLT applies the LT predicate on the "emoji" field.
func EmojiLT(v string) predicate.Agent {
	return predicate.Agent(sql.FieldLT(FieldEmoji, v))
}

// EmojiLTE applies the LTE predicate on the "emoji" field.
func EmojiLTE(v string) predicate.Agent {
	return predicate.Agent(sql.FieldLTE(FieldEmoji, v))
}

// EmojiContains applies the Contains predicate on the "emoji" field.
func EmojiContains(v string) predicate.Agent {
	return predicate.Agent(sql.FieldContains(FieldEmoji, v))
}

// EmojiHasPrefix applies the HasPrefix predicate on the "emoji" field.
func EmojiHasPrefix(v string) predicate.Agent {
	return predicate.Agent(sql.FieldHasPrefix(FieldEmoji, v))
}

// EmojiHasSuffix applies the HasSuffix predicate on the "emoji" field.
func EmojiHasSuffix(v string) predicate.Agent {
	return predicate.Agent(sql.FieldHasSuffix(FieldEmoji, v))
}

// EmojiIsNil applies the IsNil predicate on the "emoji" field.
func EmojiIsNil() predicate.Agent {
	return predicate.Agent(sql.FieldIsNull(FieldEmoji))
}

// EmojiNotNil applies the NotNil predicate on the "emoji" field.
func EmojiNotNil() predicate.Agent {
	return predicate.Agent(sql.FieldNotNull(FieldEmoji))
}

// EmojiEqualFold applies the EqualFold predicate on the "emoji" field.
func EmojiEqualFold(v string) predicate.Agent {
	return predicate.Agent(sql.FieldEqualFold(FieldEmoji, v))
}

// EmojiContainsFold applies the ContainsFold predicate on the "emoji" field.
func EmojiContainsFold(v string) predicate.Agent {
	return predicate.Agent(sql.FieldContainsFold(FieldEmoji, v))
}

// DescriptionEQ applies the EQ predicate on the "description" field.
func DescriptionEQ(v string) predicate.Agent {
	return predicate.Agent(sql.FieldEQ(FieldDescription, v))
}

// DescriptionNEQ applies the NEQ predicate on the "description" field.
func DescriptionNEQ(v string) predicate.Agent {
	return predicate.Agent(sql.FieldNEQ(FieldDescription, v))
}

// DescriptionIn applies the In predicate on the "description" field.
func DescriptionIn(vs ...string) predicate.Agent {
	return predicate.Agent(sql.FieldIn(FieldDescription, vs...))
}

// DescriptionNotIn applies the NotIn predicate on the "description" field.
func DescriptionNotIn(vs ...string) predicate.Agent {
	return predicate.Agent(sql.FieldNotIn(FieldDescription, vs...))
}

// DescriptionGT applies the GT predicate on the "description" field.
func DescriptionGT(v string) predicate.Agent {
	return predicate.Agent(sql.FieldGT(FieldDescription, v))
}

// DescriptionGTE applies the GTE predicate on the "description" field.
func DescriptionGTE(v string) predicate.Agent {
	return predicate.Agent(sql.FieldGTE(FieldDescription, v))
}

// DescriptionLT applies the LT predicate on the "description" field.
func DescriptionLT(v string) predicate.Agent {
	return predicate.Agent(sql.FieldLT(FieldDescription, v))
}

// DescriptionLTE applies the LTE predicate on the "description" field.
func DescriptionLTE(v string) predicate.Agent {
	return predicate.Agent(sql.FieldLTE(FieldDescription, v))
}

// DescriptionContains applies the Contains predicate on the "description" field.
func DescriptionContains(v string) predicate.Agent {
	return predicate.Agent(sql.FieldContains(FieldDescription, v))
}

// DescriptionHasPrefix applies the HasPrefix predicate on the "description" field.
func DescriptionHasPrefix(v string) predicate.Agent {
	return predicate.Agent(sql.FieldHasPrefix(FieldDescription, v))
}

// DescriptionHasSuffix applies the HasSuffix predicate on the "description" field.
func DescriptionHasSuffix(v string) predicate.Agent {
	return predicate.Agent(sql.FieldHasSuffix(FieldDescription, v))
}

// DescriptionIsNil applies the IsNil predicate on the "description" field.
func DescriptionIsNil() predicate.Agent {
	return predicate.Agent(sql.FieldIsNull(FieldDescription))
}

// DescriptionNotNil applies the NotNil predicate on the "description" field.
func DescriptionNotNil() predicate.Agent {
	return predicate.Agent(sql.FieldNotNull(FieldDescription))
}

// DescriptionEqualFold applies the EqualFold predicate on the "description" field.
func DescriptionEqualFold(v string) predicate.Agent {
	return predicate.Agent(sql.FieldEqualFold(FieldDescription, v))
}

// DescriptionContainsFold applies the ContainsFold predicate on the "description" field.
func DescriptionContainsFold(v string) predicate.Agent {
	return predicate.Agent(sql.FieldContainsFold(FieldDescription, v))
}

// ModelEQ applies the EQ predicate on the "model" field.
func ModelEQ(v Model) predicate.Agent {
	return predicate.Agent(sql.FieldEQ(FieldModel, v))
}

// ModelNEQ applies the NEQ predicate on the "model" field.
func ModelNEQ(v Model) predicate.Agent {
	return predicate.Agent(sql.FieldNEQ(FieldModel, v))
}

// ModelIn applies the In predicate on the "model" field.
func ModelIn(vs ...Model) predicate.Agent {
	return predicate.Agent(sql.FieldIn(FieldModel, vs...))
}

// ModelNotIn applies the NotIn predicate on the "model" field.
func ModelNotIn(vs ...Model) predicate.Agent {
	return predicate.Agent(sql.FieldNotIn(FieldModel, vs...))
}

// RuntimeEQ applies the EQ predicate on the "runtime" field.
func RuntimeEQ(v Runtime) predicate.Agent {
	return predicate.Agent(sql.FieldEQ(FieldRuntime, v))
}

// RuntimeNEQ applies the NEQ predicate on the "runtime" field.
func RuntimeNEQ(v Runtime) predicate.Agent {
	return predicate.Agent(sql.FieldNEQ(FieldRuntime, v))
}

// RuntimeIn applies the In predicate on the "runtime" field.
func RuntimeIn(vs ...Runtime) predicate.Agent {
	return predicate.Agent(sql.FieldIn(FieldRuntime, vs...))
}

// RuntimeNotIn applies the NotIn predicate on the "runtime" field.
func RuntimeNotIn(vs ...Runtime) predicate.Agent {
	return predicate.Agent(sql.FieldNotIn(FieldRuntime, vs...))
}

// RuntimeIsNil applies the IsNil predicate on the "runtime" field.
func RuntimeIsNil() predicate.Agent {
	return predicate.Agent(sql.FieldIsNull(FieldRuntime))
}

// RuntimeNotNil applies the NotNil predicate on the "runtime" field.
func RuntimeNotNil() predicate.Agent {
	return predicate.Agent(sql.FieldNotNull(FieldRuntime))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.Agent {
	return predicate.Agent(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.Agent {
	return predicate.Agent(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.Agent {
	return predicate.Agent(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.Agent {
	return predicate.Agent(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.Agent {
	return predicate.Agent(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.Agent {
	return predicate.Agent(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.Agent {
	return predicate.Agent(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.Agent {
	return predicate.Agent(sql.FieldLTE(FieldCreatedAt, v))
}

// HasTags applies the HasEdge predicate on the "tags" edge.
func HasTags() predicate.Agent {
	return predicate.Agent(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2M, false, TagsTable, TagsPrimaryKey...),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasTagsWith applies the HasEdge predicate on the "tags" edge with a given conditions (other predicates).
func HasTagsWith(preds ...predicate.Tag) predicate.Agent {
	return predicate.Agent(func(s *sql.Selector) {
		step := newTagsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Agent) predicate.Agent {
	return predicate.Agent(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Agent) predicate.Agent {
	return predicate.Agent(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Agent) predicate.Agent {
	return predicate.Agent(sql.NotPredicates(p))
}
