// Code generated by ent, DO NOT EDIT.

package reaction

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the reaction type in the database.
	Label = "reaction"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldEmoji holds the string denoting the emoji field in the database.
	FieldEmoji = "emoji"
	// FieldFromAgent holds the string denoting the from_agent field in the database.
	FieldFromAgent = "from_agent"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// EdgeMessage holds the string denoting the message edge name in mutations.
	EdgeMessage = "message"
	// Table holds the table name of the reaction in the database.
	Table = "reactions"
	// MessageTable is the table that holds the message relation/edge.
	MessageTable = "reactions"
	// MessageInverseTable is the table name for the Message entity.
	// It exists in this package in order to avoid circular dependency with the "message" package.
	MessageInverseTable = "messages"
	// MessageColumn is the table column denoting the message relation/edge.
	MessageColumn = "message_reactions"
)

// Columns holds all SQL columns for reaction fields.
var Columns = []string{
	FieldID,
	FieldEmoji,
	FieldFromAgent,
	FieldCreatedAt,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the "reactions"
// table and are not defined as standalone fields in the schema.
var ForeignKeys = []string{
	"message_reactions",
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	for i := range ForeignKeys {
		if column == ForeignKeys[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)

// OrderOption defines the ordering options for the Reaction queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByEmoji orders the results by the emoji field.
func ByEmoji(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEmoji, opts...).ToFunc()
}

// ByFromAgent orders the results by the from_agent field.
func ByFromAgent(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFromAgent, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByMessageField orders the results by message field.
func ByMessageField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newMessageStep(), sql.OrderByField(field, opts...))
	}
}
func newMessageStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(MessageInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, MessageTable, MessageColumn),
	)
}
