// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/guion-opensource/ttal-cli/ent/predicate"
	"github.com/guion-opensource/ttal-cli/ent/project"
	"github.com/guion-opensource/ttal-cli/ent/tag"
)

// ProjectUpdate is the builder for updating Project entities.
type ProjectUpdate struct {
	config
	hooks    []Hook
	mutation *ProjectMutation
}

// Where appends a list predicates to the ProjectUpdate builder.
func (_u *ProjectUpdate) Where(ps ...predicate.Project) *ProjectUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetAlias sets the "alias" field.
func (_u *ProjectUpdate) SetAlias(v string) *ProjectUpdate {
	_u.mutation.SetAlias(v)
	return _u
}

// SetNillableAlias sets the "alias" field if the given value is not nil.
func (_u *ProjectUpdate) SetNillableAlias(v *string) *ProjectUpdate {
	if v != nil {
		_u.SetAlias(*v)
	}
	return _u
}

// SetName sets the "name" field.
func (_u *ProjectUpdate) SetName(v string) *ProjectUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *ProjectUpdate) SetNillableName(v *string) *ProjectUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *ProjectUpdate) SetDescription(v string) *ProjectUpdate {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *ProjectUpdate) SetNillableDescription(v *string) *ProjectUpdate {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// ClearDescription clears the value of the "description" field.
func (_u *ProjectUpdate) ClearDescription() *ProjectUpdate {
	_u.mutation.ClearDescription()
	return _u
}

// SetPath sets the "path" field.
func (_u *ProjectUpdate) SetPath(v string) *ProjectUpdate {
	_u.mutation.SetPath(v)
	return _u
}

// SetNillablePath sets the "path" field if the given value is not nil.
func (_u *ProjectUpdate) SetNillablePath(v *string) *ProjectUpdate {
	if v != nil {
		_u.SetPath(*v)
	}
	return _u
}

// ClearPath clears the value of the "path" field.
func (_u *ProjectUpdate) ClearPath() *ProjectUpdate {
	_u.mutation.ClearPath()
	return _u
}

// SetRepo sets the "repo" field.
func (_u *ProjectUpdate) SetRepo(v string) *ProjectUpdate {
	_u.mutation.SetRepo(v)
	return _u
}

// SetNillableRepo sets the "repo" field if the given value is not nil.
func (_u *ProjectUpdate) SetNillableRepo(v *string) *ProjectUpdate {
	if v != nil {
		_u.SetRepo(*v)
	}
	return _u
}

// ClearRepo clears the value of the "repo" field.
func (_u *ProjectUpdate) ClearRepo() *ProjectUpdate {
	_u.mutation.ClearRepo()
	return _u
}

// SetRepoType sets the "repo_type" field.
func (_u *ProjectUpdate) SetRepoType(v project.RepoType) *ProjectUpdate {
	_u.mutation.SetRepoType(v)
	return _u
}

// SetNillableRepoType sets the "repo_type" field if the given value is not nil.
func (_u *ProjectUpdate) SetNillableRepoType(v *project.RepoType) *ProjectUpdate {
	if v != nil {
		_u.SetRepoType(*v)
	}
	return _u
}

// ClearRepoType clears the value of the "repo_type" field.
func (_u *ProjectUpdate) ClearRepoType() *ProjectUpdate {
	_u.mutation.ClearRepoType()
	return _u
}

// SetOwner sets the "owner" field.
func (_u *ProjectUpdate) SetOwner(v string) *ProjectUpdate {
	_u.mutation.SetOwner(v)
	return _u
}

// SetNillableOwner sets the "owner" field if the given value is not nil.
func (_u *ProjectUpdate) SetNillableOwner(v *string) *ProjectUpdate {
	if v != nil {
		_u.SetOwner(*v)
	}
	return _u
}

// ClearOwner clears the value of the "owner" field.
func (_u *ProjectUpdate) ClearOwner() *ProjectUpdate {
	_u.mutation.ClearOwner()
	return _u
}

// SetArchivedAt sets the "archived_at" field.
func (_u *ProjectUpdate) SetArchivedAt(v time.Time) *ProjectUpdate {
	_u.mutation.SetArchivedAt(v)
	return _u
}

// SetNillableArchivedAt sets the "archived_at" field if the given value is not nil.
func (_u *ProjectUpdate) SetNillableArchivedAt(v *time.Time) *ProjectUpdate {
	if v != nil {
		_u.SetArchivedAt(*v)
	}
	return _u
}

// ClearArchivedAt clears the value of the "archived_at" field.
func (_u *ProjectUpdate) ClearArchivedAt() *ProjectUpdate {
	_u.mutation.ClearArchivedAt()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ProjectUpdate) SetUpdatedAt(v time.Time) *ProjectUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// AddTagIDs adds the "tags" edge to the Tag entity by IDs.
func (_u *ProjectUpdate) AddTagIDs(ids ...int) *ProjectUpdate {
	_u.mutation.AddTagIDs(ids...)
	return _u
}

// AddTags adds the "tags" edges to the Tag entity.
func (_u *ProjectUpdate) AddTags(v ...*Tag) *ProjectUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddTagIDs(ids...)
}

// Mutation returns the ProjectMutation object of the builder.
func (_u *ProjectUpdate) Mutation() *ProjectMutation {
	return _u.mutation
}

// ClearTags clears all "tags" edges to the Tag entity.
func (_u *ProjectUpdate) ClearTags() *ProjectUpdate {
	_u.mutation.ClearTags()
	return _u
}

// RemoveTagIDs removes the "tags" edge to Tag entities by IDs.
func (_u *ProjectUpdate) RemoveTagIDs(ids ...int) *ProjectUpdate {
	_u.mutation.RemoveTagIDs(ids...)
	return _u
}

// RemoveTags removes "tags" edges to Tag entities.
func (_u *ProjectUpdate) RemoveTags(v ...*Tag) *ProjectUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveTagIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ProjectUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ProjectUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ProjectUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ProjectUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ProjectUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := project.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ProjectUpdate) check() error {
	if v, ok := _u.mutation.Alias(); ok {
		if err := project.AliasValidator(v); err != nil {
			return &ValidationError{Name: "alias", err: fmt.Errorf(`ent: validator failed for field "Project.alias": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Name(); ok {
		if err := project.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Project.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.RepoType(); ok {
		if err := project.RepoTypeValidator(v); err != nil {
			return &ValidationError{Name: "repo_type", err: fmt.Errorf(`ent: validator failed for field "Project.repo_type": %w`, err)}
		}
	}
	return nil
}

func (_u *ProjectUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(project.Table, project.Columns, sqlgraph.NewFieldSpec(project.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Alias(); ok {
		_spec.SetField(project.FieldAlias, field.TypeString, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(project.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(project.FieldDescription, field.TypeString, value)
	}
	if _u.mutation.DescriptionCleared() {
		_spec.ClearField(project.FieldDescription, field.TypeString)
	}
	if value, ok := _u.mutation.Path(); ok {
		_spec.SetField(project.FieldPath, field.TypeString, value)
	}
	if _u.mutation.PathCleared() {
		_spec.ClearField(project.FieldPath, field.TypeString)
	}
	if value, ok := _u.mutation.Repo(); ok {
		_spec.SetField(project.FieldRepo, field.TypeString, value)
	}
	if _u.mutation.RepoCleared() {
		_spec.ClearField(project.FieldRepo, field.TypeString)
	}
	if value, ok := _u.mutation.RepoType(); ok {
		_spec.SetField(project.FieldRepoType, field.TypeEnum, value)
	}
	if _u.mutation.RepoTypeCleared() {
		_spec.ClearField(project.FieldRepoType, field.TypeEnum)
	}
	if value, ok := _u.mutation.Owner(); ok {
		_spec.SetField(project.FieldOwner, field.TypeString, value)
	}
	if _u.mutation.OwnerCleared() {
		_spec.ClearField(project.FieldOwner, field.TypeString)
	}
	if value, ok := _u.mutation.ArchivedAt(); ok {
		_spec.SetField(project.FieldArchivedAt, field.TypeTime, value)
	}
	if _u.mutation.ArchivedAtCleared() {
		_spec.ClearField(project.FieldArchivedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(project.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.TagsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   project.TagsTable,
			Columns: project.TagsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tag.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedTagsIDs(); len(nodes) > 0 && !_u.mutation.TagsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   project.TagsTable,
			Columns: project.TagsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tag.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.TagsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   project.TagsTable,
			Columns: project.TagsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tag.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{project.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ProjectUpdateOne is the builder for updating a single Project entity.
type ProjectUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ProjectMutation
}

// SetAlias sets the "alias" field.
func (_u *ProjectUpdateOne) SetAlias(v string) *ProjectUpdateOne {
	_u.mutation.SetAlias(v)
	return _u
}

// SetNillableAlias sets the "alias" field if the given value is not nil.
func (_u *ProjectUpdateOne) SetNillableAlias(v *string) *ProjectUpdateOne {
	if v != nil {
		_u.SetAlias(*v)
	}
	return _u
}

// SetName sets the "name" field.
func (_u *ProjectUpdateOne) SetName(v string) *ProjectUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *ProjectUpdateOne) SetNillableName(v *string) *ProjectUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *ProjectUpdateOne) SetDescription(v string) *ProjectUpdateOne {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *ProjectUpdateOne) SetNillableDescription(v *string) *ProjectUpdateOne {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// ClearDescription clears the value of the "description" field.
func (_u *ProjectUpdateOne) ClearDescription() *ProjectUpdateOne {
	_u.mutation.ClearDescription()
	return _u
}

// SetPath sets the "path" field.
func (_u *ProjectUpdateOne) SetPath(v string) *ProjectUpdateOne {
	_u.mutation.SetPath(v)
	return _u
}

// SetNillablePath sets the "path" field if the given value is not nil.
func (_u *ProjectUpdateOne) SetNillablePath(v *string) *ProjectUpdateOne {
	if v != nil {
		_u.SetPath(*v)
	}
	return _u
}

// ClearPath clears the value of the "path" field.
func (_u *ProjectUpdateOne) ClearPath() *ProjectUpdateOne {
	_u.mutation.ClearPath()
	return _u
}

// SetRepo sets the "repo" field.
func (_u *ProjectUpdateOne) SetRepo(v string) *ProjectUpdateOne {
	_u.mutation.SetRepo(v)
	return _u
}

// SetNillableRepo sets the "repo" field if the given value is not nil.
func (_u *ProjectUpdateOne) SetNillableRepo(v *string) *ProjectUpdateOne {
	if v != nil {
		_u.SetRepo(*v)
	}
	return _u
}

// ClearRepo clears the value of the "repo" field.
func (_u *ProjectUpdateOne) ClearRepo() *ProjectUpdateOne {
	_u.mutation.ClearRepo()
	return _u
}

// SetRepoType sets the "repo_type" field.
func (_u *ProjectUpdateOne) SetRepoType(v project.RepoType) *ProjectUpdateOne {
	_u.mutation.SetRepoType(v)
	return _u
}

// SetNillableRepoType sets the "repo_type" field if the given value is not nil.
func (_u *ProjectUpdateOne) SetNillableRepoType(v *project.RepoType) *ProjectUpdateOne {
	if v != nil {
		_u.SetRepoType(*v)
	}
	return _u
}

// ClearRepoType clears the value of the "repo_type" field.
func (_u *ProjectUpdateOne) ClearRepoType() *ProjectUpdateOne {
	_u.mutation.ClearRepoType()
	return _u
}

// SetOwner sets the "owner" field.
func (_u *ProjectUpdateOne) SetOwner(v string) *ProjectUpdateOne {
	_u.mutation.SetOwner(v)
	return _u
}

// SetNillableOwner sets the "owner" field if the given value is not nil.
func (_u *ProjectUpdateOne) SetNillableOwner(v *string) *ProjectUpdateOne {
	if v != nil {
		_u.SetOwner(*v)
	}
	return _u
}

// ClearOwner clears the value of the "owner" field.
func (_u *ProjectUpdateOne) ClearOwner() *ProjectUpdateOne {
	_u.mutation.ClearOwner()
	return _u
}

// SetArchivedAt sets the "archived_at" field.
func (_u *ProjectUpdateOne) SetArchivedAt(v time.Time) *ProjectUpdateOne {
	_u.mutation.SetArchivedAt(v)
	return _u
}

// SetNillableArchivedAt sets the "archived_at" field if the given value is not nil.
func (_u *ProjectUpdateOne) SetNillableArchivedAt(v *time.Time) *ProjectUpdateOne {
	if v != nil {
		_u.SetArchivedAt(*v)
	}
	return _u
}

// ClearArchivedAt clears the value of the "archived_at" field.
func (_u *ProjectUpdateOne) ClearArchivedAt() *ProjectUpdateOne {
	_u.mutation.ClearArchivedAt()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ProjectUpdateOne) SetUpdatedAt(v time.Time) *ProjectUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// AddTagIDs adds the "tags" edge to the Tag entity by IDs.
func (_u *ProjectUpdateOne) AddTagIDs(ids ...int) *ProjectUpdateOne {
	_u.mutation.AddTagIDs(ids...)
	return _u
}

// AddTags adds the "tags" edges to the Tag entity.
func (_u *ProjectUpdateOne) AddTags(v ...*Tag) *ProjectUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddTagIDs(ids...)
}

// Mutation returns the ProjectMutation object of the builder.
func (_u *ProjectUpdateOne) Mutation() *ProjectMutation {
	return _u.mutation
}

// ClearTags clears all "tags" edges to the Tag entity.
func (_u *ProjectUpdateOne) ClearTags() *ProjectUpdateOne {
	_u.mutation.ClearTags()
	return _u
}

// RemoveTagIDs removes the "tags" edge to Tag entities by IDs.
func (_u *ProjectUpdateOne) RemoveTagIDs(ids ...int) *ProjectUpdateOne {
	_u.mutation.RemoveTagIDs(ids...)
	return _u
}

// RemoveTags removes "tags" edges to Tag entities.
func (_u *ProjectUpdateOne) RemoveTags(v ...*Tag) *ProjectUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveTagIDs(ids...)
}

// Where appends a list predicates to the ProjectUpdate builder.
func (_u *ProjectUpdateOne) Where(ps ...predicate.Project) *ProjectUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ProjectUpdateOne) Select(field string, fields ...string) *ProjectUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Project entity.
func (_u *ProjectUpdateOne) Save(ctx context.Context) (*Project, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ProjectUpdateOne) SaveX(ctx context.Context) *Project {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ProjectUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ProjectUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ProjectUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := project.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ProjectUpdateOne) check() error {
	if v, ok := _u.mutation.Alias(); ok {
		if err := project.AliasValidator(v); err != nil {
			return &ValidationError{Name: "alias", err: fmt.Errorf(`ent: validator failed for field "Project.alias": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Name(); ok {
		if err := project.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Project.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.RepoType(); ok {
		if err := project.RepoTypeValidator(v); err != nil {
			return &ValidationError{Name: "repo_type", err: fmt.Errorf(`ent: validator failed for field "Project.repo_type": %w`, err)}
		}
	}
	return nil
}

func (_u *ProjectUpdateOne) sqlSave(ctx context.Context) (_node *Project, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(project.Table, project.Columns, sqlgraph.NewFieldSpec(project.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Project.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, project.FieldID)
		for _, f := range fields {
			if !project.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != project.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Alias(); ok {
		_spec.SetField(project.FieldAlias, field.TypeString, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(project.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(project.FieldDescription, field.TypeString, value)
	}
	if _u.mutation.DescriptionCleared() {
		_spec.ClearField(project.FieldDescription, field.TypeString)
	}
	if value, ok := _u.mutation.Path(); ok {
		_spec.SetField(project.FieldPath, field.TypeString, value)
	}
	if _u.mutation.PathCleared() {
		_spec.ClearField(project.FieldPath, field.TypeString)
	}
	if value, ok := _u.mutation.Repo(); ok {
		_spec.SetField(project.FieldRepo, field.TypeString, value)
	}
	if _u.mutation.RepoCleared() {
		_spec.ClearField(project.FieldRepo, field.TypeString)
	}
	if value, ok := _u.mutation.RepoType(); ok {
		_spec.SetField(project.FieldRepoType, field.TypeEnum, value)
	}
	if _u.mutation.RepoTypeCleared() {
		_spec.ClearField(project.FieldRepoType, field.TypeEnum)
	}
	if value, ok := _u.mutation.Owner(); ok {
		_spec.SetField(project.FieldOwner, field.TypeString, value)
	}
	if _u.mutation.OwnerCleared() {
		_spec.ClearField(project.FieldOwner, field.TypeString)
	}
	if value, ok := _u.mutation.ArchivedAt(); ok {
		_spec.SetField(project.FieldArchivedAt, field.TypeTime, value)
	}
	if _u.mutation.ArchivedAtCleared() {
		_spec.ClearField(project.FieldArchivedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(project.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.TagsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   project.TagsTable,
			Columns: project.TagsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tag.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedTagsIDs(); len(nodes) > 0 && !_u.mutation.TagsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   project.TagsTable,
			Columns: project.TagsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tag.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.TagsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   project.TagsTable,
			Columns: project.TagsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tag.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Project{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{project.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
