package doctor

import (
	"fmt"
	"os"
	"path/filepath"

	"github.com/tta-lab/ttal-cli/internal/config"
	"github.com/tta-lab/ttal-cli/internal/humanfs"
)

// checkHumans validates humans.toml configuration.
func checkHumans(fix bool) Section {
	section := Section{Name: "Humans"}

	humansPath, err := config.HumansPath()
	if err != nil {
		section.add(LevelError, "humans_path", fmt.Sprintf("cannot determine humans path: %v", err))
		return section
	}

	if _, err := os.Stat(humansPath); os.IsNotExist(err) {
		if fix {
			section.add(LevelWarn, "humans_toml", "humans.toml not found — generating from legacy config")
			if err := fixHumans(humansPath); err != nil {
				section.add(LevelError, "humans_fix", fmt.Sprintf("failed to generate humans.toml: %v", err))
			} else {
				section.add(LevelOK, "humans_fix", fmt.Sprintf("generated %s — review and apply", humansPath))
			}
		} else {
			section.add(LevelWarn, "humans_toml", fmt.Sprintf(
				"humans.toml not found (run: ttal doctor --fix to generate from legacy config)"))
		}
		return section
	}

	humans, err := humanfs.Load(humansPath)
	if err != nil {
		section.add(LevelError, "humans_toml", fmt.Sprintf("invalid humans.toml: %v", err))
		return section
	}

	section.add(LevelOK, "humans_toml", fmt.Sprintf("%d humans loaded", len(humans)))

	// Check admin count
	adminCount := 0
	for _, h := range humans {
		if h.Admin {
			adminCount++
		}
	}
	switch {
	case adminCount == 0:
		section.add(LevelError, "admin", "no admin found (exactly one required)")
	case adminCount > 1:
		section.add(LevelError, "admin", fmt.Sprintf("%d admins found (exactly one required)", adminCount))
	default:
		section.add(LevelOK, "admin", "exactly one admin configured")
	}

	// Check each human has required fields
	for _, h := range humans {
		if h.Name == "" {
			section.add(LevelError, "human:"+h.Alias, "name is required")
		}
		if h.TelegramChatID == "" {
			section.add(LevelError, "human:"+h.Alias, "telegram_chat_id is required")
		}
	}

	return section
}

// fixHumans generates a humans.toml from legacy config fields.
func fixHumans(humansPath string) error {
	cfg, err := config.Load()
	if err != nil {
		return fmt.Errorf("load config: %w", err)
	}

	// Use admin human if available
	if cfg.AdminHuman == nil {
		return fmt.Errorf("cannot derive human: no admin human found (ensure humans.toml exists or legacy config has user.name and teams.*.chat_id)")
	}

	h := cfg.AdminHuman

	// Write as .generated file to avoid overwriting existing
	outPath := humansPath + ".generated"
	content := fmt.Sprintf(`# Generated by ttal doctor --fix
# Review and rename to humans.toml to apply

[%s]
name = %q
age = %d
pronouns = %q
telegram_chat_id = %q
matrix_user_id = %q
admin = %t
`, h.Alias, h.Name, h.Age, h.Pronouns, h.TelegramChatID, h.MatrixUserID, h.Admin)

	if err := os.MkdirAll(filepath.Dir(outPath), 0o755); err != nil {
		return fmt.Errorf("create dir: %w", err)
	}
	return os.WriteFile(outPath, []byte(content), 0o644)
}
