package doctor

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/BurntSushi/toml"

	"github.com/tta-lab/ttal-cli/internal/config"
	"github.com/tta-lab/ttal-cli/internal/humanfs"
)

// checkHumans validates humans.toml configuration.
func checkHumans(fix bool) Section {
	section := Section{Name: "Humans"}

	humansPath, err := config.HumansPath()
	if err != nil {
		section.add(LevelError, "humans_path", fmt.Sprintf("cannot determine humans path: %v", err))
		return section
	}

	if _, err := os.Stat(humansPath); os.IsNotExist(err) {
		if fix {
			section.add(LevelWarn, "humans_toml", "humans.toml not found — generating from legacy config")
			if err := fixHumans(humansPath); err != nil {
				section.add(LevelError, "humans_fix", fmt.Sprintf("failed to generate humans.toml: %v", err))
			} else {
				section.add(LevelOK, "humans_fix", fmt.Sprintf("generated %s — review and apply", humansPath))
			}
		} else {
			section.add(LevelWarn, "humans_toml",
				"humans.toml not found (run: ttal doctor --fix to generate from legacy config)")
		}
		return section
	}

	humans, err := humanfs.Load(humansPath)
	if err != nil {
		section.add(LevelError, "humans_toml", fmt.Sprintf("invalid humans.toml: %v", err))
		return section
	}

	section.add(LevelOK, "humans_toml", fmt.Sprintf("%d humans loaded", len(humans)))

	// Check admin count
	adminCount := 0
	for _, h := range humans {
		if h.Admin {
			adminCount++
		}
	}
	switch {
	case adminCount == 0:
		section.add(LevelError, "admin", "no admin found (exactly one required)")
	case adminCount > 1:
		section.add(LevelError, "admin", fmt.Sprintf("%d admins found (exactly one required)", adminCount))
	default:
		section.add(LevelOK, "admin", "exactly one admin configured")
	}

	// Check each human has required fields
	for _, h := range humans {
		if h.Name == "" {
			section.add(LevelError, "human:"+h.Alias, "name is required")
		}
		if h.TelegramChatID == "" {
			section.add(LevelError, "human:"+h.Alias, "telegram_chat_id is required")
		}
	}

	return section
}

// fixHumans generates a humans.toml from legacy config fields.
// Bypasses config.Load() since humans.toml may be absent — reads config.toml directly.
func fixHumans(humansPath string) error {
	cfgPath, err := config.Path()
	if err != nil {
		return fmt.Errorf("config path: %w", err)
	}

	// Decode raw config.toml for legacy fields.
	var raw struct {
		User   string `toml:"name"`
		Teams  map[string]struct {
			ChatID  string `toml:"chat_id"`
			Matrix  *struct {
				HumanUserID string `toml:"human_user_id"`
			} `toml:"matrix"`
		} `toml:"teams"`
	}
	if _, err := toml.DecodeFile(cfgPath, &raw); err != nil {
		return fmt.Errorf("read %s: %w", cfgPath, err)
	}

	team, ok := raw.Teams["default"]
	if !ok {
		return fmt.Errorf("no [teams.default] in %s", cfgPath)
	}

	name := raw.User
	if name == "" {
		name = os.Getenv("USER")
	}
	if name == "" {
		return fmt.Errorf("cannot derive user name from %s or $USER", cfgPath)
	}
	if team.ChatID == "" {
		return fmt.Errorf("[teams.default].chat_id is empty in %s — cannot migrate", cfgPath)
	}

	matrixUserID := ""
	if team.Matrix != nil {
		matrixUserID = team.Matrix.HumanUserID
	}

	alias := strings.ToLower(name)
	content := fmt.Sprintf(`# Generated by ttal doctor --fix
# Review, fill in age/pronouns, then rename to humans.toml to apply

[%s]
name = %q
age = 0
pronouns = ""
telegram_chat_id = %q
matrix_user_id = %q
admin = true
`, alias, name, team.ChatID, matrixUserID)

	outPath := humansPath + ".generated"
	if err := os.MkdirAll(filepath.Dir(outPath), 0o755); err != nil {
		return fmt.Errorf("create dir: %w", err)
	}
	return os.WriteFile(outPath, []byte(content), 0o644)
}
