// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Agent is the predicate function for agent builders.
type Agent func(*sql.Selector)

// Project is the predicate function for project builders.
type Project func(*sql.Selector)
